import { cn } from "@heroui/react"

/**
 * App-owned public-site boundaries; Grammar component anatomy remains untouched. The shell chrome
 * is written as utilities on grammar tokens -- the values the flat selectors in globals.css used to
 * carry -- while `site-section-intro` and `site-action-row` keep their class marker because the
 * home-area rules in globals.css still select them (the home block owns those rules), and
 * `site-main` keeps its marker because commercial-corporate.module.css still selects it.
 */
export const SITE_CLASS_NAMES = {
    sectionIntro: cn(
        "site-section-intro",
        "max-w-[50rem]",
        "[@media(max-width:48rem)]:flex-col",
        "[@media(max-width:48rem)]:items-start!",
    ),
    sectionIntroInverse: cn(
        "site-section-intro",
        "max-w-[50rem]",
        "text-surface",
        "[@media(max-width:48rem)]:flex-col",
        "[@media(max-width:48rem)]:items-start!",
    ),
    processFlow: "process-flow",
    processFlowStep: "process-flow__step",
    processFlowIndex: "process-flow__index",
    processFlowNode: "process-flow__node",
    processFlowCopy: "process-flow__copy",
    main: cn("site-main", "focus:outline-none"),
    footer: cn(
        "border-t",
        "border-landing-inverse-line",
        "bg-landing-inverse",
        "pt-16",
        "pb-8",
        "text-surface",
        "[--foreground:var(--surface)]",
        "[--muted:var(--landing-inverse-muted)]",
        "[--starci-core-foreground:var(--surface)]",
        "[--starci-core-muted:var(--landing-inverse-muted)]",
        "[--nivo-brand-ink:var(--surface)]",
        "[--nivo-brand-accent:var(--accent)]",
        "forced-colors:bg-[Canvas]",
        "forced-colors:text-[CanvasText]",
    ),
    footerInner: cn(
        "grid",
        "grid-cols-[minmax(13rem,0.75fr)_minmax(0,_1.5fr)]",
        "gap-16",
        "[@media(max-width:64rem)]:grid-cols-1",
    ),
    footerIdentity: cn(
        "flex",
        "max-w-80",
        "flex-col",
        "items-start",
        "gap-4",
        "[&>a]:inline-flex",
        "[&>a]:min-h-11",
        "[&>a]:items-center",
    ),
    footerDirectory: cn(
        "grid",
        "grid-cols-4",
        "gap-8",
        "[&_nav>p]:mb-4",
        "[&_nav>p]:uppercase",
        "[&_nav>p]:tracking-[0.08em]",
        "[&_ul]:grid",
        "[&_ul]:gap-2",
        "[&_a]:text-surface",
        "[@media(max-width:64rem)]:grid-cols-2",
    ),
    footerLegal: cn(
        "col-span-full",
        "flex",
        "items-center",
        "justify-between",
        "gap-4",
        "border-t",
        "border-landing-inverse-line",
        "pt-6",
        "text-landing-inverse-muted",
        "[&_a]:text-surface",
        "[@media(max-width:48rem)]:flex-col",
        "[@media(max-width:48rem)]:items-start",
    ),
    header: cn(
        "sticky",
        "top-0",
        "z-40",
        "border-b",
        "border-landing-header-line",
        "bg-landing-header-canvas",
        "backdrop-blur-lg",
    ),
    headerBar: cn(
        "min-h-(--landing-header-height)",
        "grid",
        "grid-cols-[auto_minmax(0,_1fr)_auto]",
        "items-center",
        "gap-8",
        "[@media(max-width:64rem)]:grid-cols-[1fr_auto]",
    ),
    headerBrand: cn("inline-flex", "min-w-[6.5rem]", "min-h-11", "items-center"),
    headerDesktopNavigation: cn("min-w-0", "[@media(max-width:64rem)]:hidden"),
    navigationList: cn("flex", "items-center", "justify-center", "gap-[clamp(0.35rem,1.5vw,1.5rem)]"),
    navigationMobileList: cn(
        "[@media(max-width:64rem)]:grid",
        "[@media(max-width:64rem)]:gap-1",
        "[@media(max-width:64rem)]:[&>li>a]:w-full!",
        "[@media(max-width:64rem)]:[&>li>a]:min-h-12!",
        "[@media(max-width:64rem)]:[&>li>a]:justify-between",
        "[@media(max-width:64rem)]:[&>li>a]:px-0!",
        "[@media(max-width:64rem)]:[&>li>a]:border-b",
        "[@media(max-width:64rem)]:[&>li>a]:border-border",
    ),
    navigationGroup: cn("relative"),
    navigationSummary: cn(
        "min-h-11",
        "inline-flex",
        "items-center",
        "gap-2",
        "px-2",
        "cursor-pointer",
        "text-[0.875rem]",
        "font-semibold",
        "list-none",
        "[&::-webkit-details-marker]:hidden",
        "after:inline-block",
        "after:size-[0.4rem]",
        "after:content-['']",
        "after:[transform:rotate(45deg)_translateY(-0.12rem)]",
        "after:border-r-[1.5px]",
        "after:border-b-[1.5px]",
        "after:border-current",
        "[details[open]>&]:after:[transform:rotate(225deg)_translate(-0.1rem,-0.1rem)]",
    ),
    navigationSummaryMobile: cn(
        "[@media(max-width:64rem)]:w-full",
        "[@media(max-width:64rem)]:min-h-12",
        "[@media(max-width:64rem)]:justify-between",
        "[@media(max-width:64rem)]:px-0",
        "[@media(max-width:64rem)]:border-b",
        "[@media(max-width:64rem)]:border-border",
    ),
    navigationPanel: cn(
        "absolute",
        "top-[calc(100%+0.5rem)]",
        "left-1/2",
        "z-[4]",
        "min-w-56",
        "-translate-x-1/2",
        "rounded-xl",
        "border",
        "border-border",
        "bg-surface",
        "p-2",
        "shadow-landing-popover",
        "[&_a]:w-full!",
        "[&_a]:justify-start",
    ),
    navigationPanelMobile: cn(
        "[@media(max-width:64rem)]:grid",
        "[@media(max-width:64rem)]:gap-1",
        "[@media(max-width:64rem)]:border-l",
        "[@media(max-width:64rem)]:border-accent",
        "[@media(max-width:64rem)]:pt-2",
        "[@media(max-width:64rem)]:pr-0",
        "[@media(max-width:64rem)]:pb-3",
        "[@media(max-width:64rem)]:pl-4",
    ),
    headerActions: cn("flex", "items-center", "gap-3", "[&>a]:min-h-11", "[@media(max-width:64rem)]:hidden"),
    headerMenuTrigger: cn(
        "hidden",
        "[@media(max-width:64rem)]:grid",
        "[@media(max-width:64rem)]:size-12",
        "[@media(max-width:64rem)]:cursor-pointer",
        "[@media(max-width:64rem)]:content-center",
        "[@media(max-width:64rem)]:justify-items-center",
        "[@media(max-width:64rem)]:gap-[0.3rem]",
        "[@media(max-width:64rem)]:rounded-full",
        "[@media(max-width:64rem)]:border",
        "[@media(max-width:64rem)]:border-border",
        "[@media(max-width:64rem)]:bg-surface",
        "[@media(max-width:64rem)]:p-0",
        "[@media(max-width:64rem)]:text-background-inverse",
        "[&>span]:w-[1.15rem]",
        "[&>span]:h-[2px]",
        "[&>span]:bg-current",
    ),
    headerMobileNavigation: cn(
        "hidden",
        "[@media(max-width:64rem)]:grid",
        "[@media(max-width:64rem)]:absolute",
        "[@media(max-width:64rem)]:inset-x-0",
        "[@media(max-width:64rem)]:top-full",
        "[@media(max-width:64rem)]:max-h-[calc(100dvh-var(--landing-header-height))]",
        "[@media(max-width:64rem)]:gap-6",
        "[@media(max-width:64rem)]:overflow-y-auto",
        "[@media(max-width:64rem)]:overscroll-contain",
        "[@media(max-width:64rem)]:border-b",
        "[@media(max-width:64rem)]:border-border",
        "[@media(max-width:64rem)]:bg-surface",
        "[@media(max-width:64rem)]:px-[max(1rem,calc((100vw-80rem)/2+2rem))]",
        "[@media(max-width:64rem)]:pt-4",
        "[@media(max-width:64rem)]:pb-8",
        "[@media(max-width:64rem)]:shadow-landing-sheet",
    ),
    headerMobileActions: cn("[@media(max-width:64rem)]:grid", "[@media(max-width:64rem)]:gap-3"),
    shell: cn(
        "min-h-dvh",
        "bg-surface",
        "text-background-inverse",
        "font-landing-page",
        "[&_a]:touch-manipulation",
        "[&_a]:[text-decoration-thickness:0.08em]",
        "[&_a]:[text-underline-offset:0.18em]!",
        "[&_:is(a,button,summary)]:focus-visible:outline-[3px]!",
        "[&_:is(a,button,summary)]:focus-visible:outline-solid!",
        "[&_:is(a,button,summary)]:focus-visible:outline-(--focus)!",
        "[&_:is(a,button,summary)]:focus-visible:outline-offset-4!",
        "[&_:is(a,button,summary)]:focus-visible:shadow-[0_0_0_2px_currentColor]!",
    ),
    skipLink: cn(
        "fixed",
        "top-3",
        "left-4",
        "z-[100]",
        "min-h-11",
        "-translate-y-[180%]",
        "rounded-lg",
        "bg-background-inverse",
        "px-4",
        "py-3",
        "font-bold",
        "text-surface",
        "focus:translate-y-0",
    ),
    screenReaderOnly: cn("sr-only"),
    actionRow: cn(
        "site-action-row",
        "flex",
        "flex-wrap",
        "items-center",
        "gap-3",
        "[&>a]:min-h-11",
        "[&>button]:min-h-11",
        "[@media(max-width:48rem)]:w-full",
        "[@media(max-width:48rem)]:flex-col",
        "[@media(max-width:48rem)]:items-stretch",
        "[@media(max-width:48rem)]:[&>a]:w-full!",
        "[@media(max-width:48rem)]:[&>a]:justify-center",
        "[@media(max-width:48rem)]:[&>button]:w-full!",
        "[@media(max-width:48rem)]:[&>button]:justify-center",
    ),
    inlineRoute: cn(
        "inline-flex",
        "flex-wrap",
        "items-center",
        "gap-[0.3em]",
        "[&>span]:inline-flex",
        "[&>span]:items-center",
        "[&>span]:gap-[0.3em]",
        "[&>span>span[aria-hidden=true]]:inline-flex",
        "[&>span>span[aria-hidden=true]]:text-landing-accent-bright",
        "[&_svg]:size-[0.82em]!",
    ),
    textAccent: cn("text-accent", "forced-colors:text-[Highlight]"),
    hero: "home-hero",
    heroContainer: "home-hero__container",
    heroCopy: "home-hero__copy",
    heroVisual: "home-hero__visual",
    heroStage: "home-hero__stage",
    heroSignal: "home-hero__signal",
    heroOrbit: "home-hero__orbit",
    heroMascot: "home-hero__mascot",
    relevance: "home-relevance",
    today: "home-today",
    todayIdentity: "home-today__identity",
    todayFocus: "home-today__focus",
    todayPrinciple: "home-today__principle",
    relevanceBody: "home-relevance__body",
    relevanceExample: "home-relevance__example",
    operatingModel: "home-operating-model",
    operatingModelLabel: "home-operating-model__label",
    operatingModelVisuals: "home-operating-model__visuals",
    operatingModelVisual: "home-operating-model__visual",
    operatingModelVisualMedia: "home-operating-model__visual-media",
    operatingModelVisualCaption: "home-operating-model__visual-caption",
    operatingModelPrinciple: "home-operating-model__principle",
    operatingModelFooter: "home-operating-model__footer",
    commercial: "home-commercial",
    commercialContainer: "home-commercial__container",
    commercialCopy: "home-commercial__copy",
    commercialRoute: "home-commercial__route",
    commercialRouteStep: "home-commercial__route-step",
    commercialRouteIndex: "home-commercial__route-index",
    commercialRouteMarker: "home-commercial__route-marker",
    commercialRouteCopy: "home-commercial__route-copy",
    commercialRouteArrow: "home-commercial__route-arrow",
    trust: "home-trust",
    trustContainer: "home-trust__container",
    trustCopy: "home-trust__copy",
    trustLinks: "home-trust__links",
    trustFuture: "home-trust__future",
    nextPath: "home-next-path",
    nextPathIdeas: "home-next-path__ideas",
    nextPathRoutes: "home-next-path__routes",
} as const
