import {
    accountingSurfaceStanding,
    formatAccountingInstant,
    formatAccountingMinor,
    formatAccountingPeriod,
} from "@/modules/accounting/accounting-workbench"
import type { useAccountingWorkbenchContext } from "./useAccountingWorkbenchContext"
import type { AccountingWorkbenchActions } from "./useAccountingWorkbench"
/** Project the AccountingWorkbenchPrimaryRegions view model. */
export const useAccountingWorkbenchPrimaryRegions = (
    context: ReturnType<typeof useAccountingWorkbenchContext>,
    actions: AccountingWorkbenchActions,
) => {
    const {
        admit,
        asOf,
        asOfDraft,
        chooseMonth,
        currency,
        evidence,
        evidenceId,
        evidenceIds,
        evidenceModel,
        fingerprint,
        format,
        intakeRevision,
        intentId,
        itemId,
        itemRevision,
        locale,
        newAttemptId,
        notStartedProofRef,
        oldAttemptId,
        period,
        periodMonth,
        policyRevision,
        ready,
        routine,
        routineCommand,
        routineModel,
        scopeStanding,
        setAsOf,
        setAsOfDraft,
        setCurrency,
        setCursor,
        setEvidenceId,
        setEvidenceIds,
        setFingerprint,
        setIntakeRevision,
        setIntentId,
        setItemId,
        setItemRevision,
        setNewAttemptId,
        setNotStartedProofRef,
        setOldAttemptId,
        setPolicyRevision,
        setSourceKind,
        setSourceRef,
        setSourceRevision,
        sourceKind,
        sourceRef,
        sourceRevision,
        summary,
        summaryModel,
        t,
    } = context
    const { onAdmit, onCommitRoutine, onRetryRoutine, workbenchCommand } = actions
    const attention =
        summaryModel === null ? [] : [...new Set(summaryModel.items.flatMap((item) => item.attentionCodes))]
    return {
        t,
        locale,
        format: {
            amount: (amountMinor: number, amountCurrency: string) =>
                formatAccountingMinor(amountMinor, amountCurrency, format),
            instant: (value: string) => formatAccountingInstant(value, format),
            period: (value: string) => formatAccountingPeriod(value, format),
        },
        scopeStanding,
        scopeReady: ready,
        periodMonth,
        setPeriodMonth: chooseMonth,
        periodLabel: period?.periodStart ?? periodMonth,
        currency,
        setCurrency,
        asOfDraft,
        setAsOfDraft,
        asOf,
        setAsOf,
        notice: workbenchCommand.notice,
        overview: {
            standing: ready ? accountingSurfaceStanding(summary.data, summaryModel !== null) : scopeStanding,
            model: summaryModel,
            attention,
            nextCursor: summaryModel?.nextCursor ?? null,
            isFetching: summary.isLoading || summary.isValidating,
            retry: () => void summary.mutate(),
            loadMore: () => setCursor(summaryModel?.nextCursor ?? null),
        },
        intake: {
            standing: ready ? accountingSurfaceStanding(evidence.data, evidenceModel !== null) : scopeStanding,
            evidenceId,
            setEvidenceId,
            sourceKind,
            setSourceKind,
            sourceRef,
            setSourceRef,
            sourceRevision,
            setSourceRevision,
            fingerprint,
            setFingerprint,
            intakeRevision,
            setIntakeRevision,
            model: evidenceModel,
            admit,
            isAdmitting: admit.isMutating || workbenchCommand.isPending(`admit-${evidenceId}`),
            onAdmit,
            reload: () => void evidence.mutate(),
        },
        routine: {
            standing: ready ? accountingSurfaceStanding(routine.data, routineModel !== null) : scopeStanding,
            intentId,
            setIntentId,
            itemId,
            setItemId,
            policyRevision,
            setPolicyRevision,
            evidenceIds,
            setEvidenceIds,
            itemRevision,
            setItemRevision,
            oldAttemptId,
            setOldAttemptId,
            notStartedProofRef,
            setNotStartedProofRef,
            newAttemptId,
            setNewAttemptId,
            model: routineModel,
            isCommitting:
                routineCommand.isMutating ||
                workbenchCommand.isPending(`routine-${intentId}`) ||
                workbenchCommand.isPending(`routine-retry-${intentId}`),
            onCommitRoutine,
            onRetryRoutine,
            reload: () => void routine.mutate(),
        },
    }
}
