import {
    salesSurfaceStanding,
    type SalesAnswerStanding,
    type SalesSurfaceStanding,
} from "@/modules/sales/sales-workbench"
import type { useSalesWorkbenchContext } from "./useSalesWorkbenchContext"
import type { useSalesWorkbenchActions } from "./useSalesWorkbenchActions"
/** Project the SalesWorkbenchSecondaryRegions responsibility for one workbench. */
export const useSalesWorkbenchSecondaryRegions = (
    context: ReturnType<typeof useSalesWorkbenchContext> & ReturnType<typeof useSalesWorkbenchActions>,
) => {
    const {
        clarificationRevision,
        clarifyAddressable,
        clarifyCommand,
        closeAddressable,
        closeEvidenceRefs,
        closeIntentId,
        closeOpportunity,
        closeOrderId,
        closeOutcome,
        closeRevision,
        command,
        commandId,
        commandModel,
        configurePolicy,
        factKind,
        factValue,
        onClarify,
        onClose,
        onConfigurePolicy,
        opportunity,
        opportunityId,
        opportunityModel,
        policy,
        policyCadence,
        policyModel,
        policyRevision,
        readiness,
        readinessModel,
        ready,
        scopeStanding,
        setClarificationRevision,
        setCloseEvidenceRefs,
        setCloseIntentId,
        setCloseOrderId,
        setCloseOutcome,
        setCloseRevision,
        setFactKind,
        setFactValue,
        setOpportunityId,
        setPolicyCadence,
        setPolicyRevision,
        workbenchCommand,
    } = context
    const regionStanding = (answer: SalesAnswerStanding | undefined, hasContent: boolean): SalesSurfaceStanding =>
        ready ? salesSurfaceStanding(answer, hasContent) : scopeStanding
    return {
        wait: {
            standing: regionStanding(opportunity.data, opportunityModel !== null),
            opportunityId,
            setOpportunityId,
            model: opportunityModel,
            isLoading: opportunity.isLoading,
            reload: () => void opportunity.mutate(),
        },
        ambiguity: {
            standing: regionStanding(command.data, commandModel !== null && commandModel.clarification !== null),
            clarification: commandModel?.clarification ?? null,
            revision: clarificationRevision,
            setRevision: setClarificationRevision,
            factKind,
            setFactKind,
            factValue,
            setFactValue,
            isClarifying: clarifyCommand.isMutating || workbenchCommand.isPending(`clarify-${commandId}`),
            addressable: clarifyAddressable,
            onClarify,
        },
        closure: {
            standing: regionStanding(opportunity.data, opportunityModel !== null),
            intentId: closeIntentId,
            setIntentId: setCloseIntentId,
            outcome: closeOutcome,
            setOutcome: setCloseOutcome,
            evidenceRefs: closeEvidenceRefs,
            setEvidenceRefs: setCloseEvidenceRefs,
            orderId: closeOrderId,
            setOrderId: setCloseOrderId,
            revision: closeRevision,
            setRevision: setCloseRevision,
            model: opportunityModel,
            isClosing: closeOpportunity.isMutating || workbenchCommand.isPending(`close-${closeIntentId}`),
            addressable: closeAddressable,
            onClose,
        },
        installation: {
            standing: regionStanding(readiness.data, readinessModel !== null),
            model: readinessModel,
            isLoading: readiness.isLoading,
            reload: () => void readiness.mutate(),
        },
        policy: {
            standing: regionStanding(policy.data, policyModel !== null),
            model: policyModel,
            revision: policyRevision,
            setRevision: setPolicyRevision,
            cadence: policyCadence,
            setCadence: setPolicyCadence,
            isConfiguring: configurePolicy.isMutating || workbenchCommand.isPending("policy"),
            onConfigure: onConfigurePolicy,
        },
    }
}
