import { fireEvent, render, screen, waitFor } from "@testing-library/react"
import { beforeEach, describe, expect, it, vi } from "vitest"
import { AcademyStudentCrm } from "./index"

type StudentFixture = { readonly id: string; readonly name: string; readonly email: string; readonly role: string; readonly status: string; readonly xp: number }
const m = vi.hoisted(() => ({ session: { state: { status: "signed-in" } }, students: { ok: true, data: { items: [] as StudentFixture[] } }, detail: { ok: true, data: undefined as unknown }, calls: { create: vi.fn(), status: vi.fn(), grant: vi.fn(), revoke: vi.fn(), list: vi.fn(), detail: vi.fn() } }))
vi.mock("next-intl", () => ({ useTranslations: () => (key: string) => key }))
vi.mock("@/modules/auth/session", () => ({ useSession: () => m.session }))
vi.mock("@/modules/api/console", () => ({ myAcademyStudents: m.calls.list, myAcademyStudentDetail: m.calls.detail, createAcademyStudent: m.calls.create, setAcademyStudentStatus: m.calls.status, grantAcademyCourseAccess: m.calls.grant, revokeAcademyCourseAccess: m.calls.revoke }))
type StudentView = { on: { openStudent: (id: string) => void; changeName: (value: string) => void; changeEmail: (value: string) => void; changePassword: (value: string) => void; createStudent: () => void; changeCourseSlug: (value: string) => void; setStatus: (status: string) => void; grantAccess: () => void; revokeAccess: () => void }; state: string; detailState: string }
vi.mock("./component", () => ({ _AcademyStudentCrm: (input: StudentView) => <><output data-testid="state">{input.state}:{input.detailState}</output><button onClick={() => input.on.openStudent("member-1")}>open</button><button onClick={() => input.on.changeName("Reader")}>name</button><button onClick={() => input.on.changeEmail("reader@example.test")}>email</button><button onClick={() => input.on.changePassword("secret")}>password</button><button onClick={input.on.createStudent}>create</button><button onClick={() => input.on.changeCourseSlug("intro")}>course</button><button onClick={() => input.on.setStatus("banned")}>ban</button><button onClick={input.on.grantAccess}>grant</button><button onClick={input.on.revokeAccess}>revoke</button></> }))

beforeEach(() => { vi.clearAllMocks(); m.students = { ok: true, data: { items: [{ id: "member-1", name: "Reader", email: "reader@example.test", role: "student", status: "active", xp: 10 }] } }; m.detail = { ok: true, data: { member: m.students.data.items[0], orders: [], courses: [] } }; m.calls.list.mockResolvedValue(m.students); m.calls.detail.mockResolvedValue(m.detail); m.calls.create.mockResolvedValue({ ok: true }); m.calls.status.mockResolvedValue({ ok: true }); m.calls.grant.mockResolvedValue({ ok: true }); m.calls.revoke.mockResolvedValue({ ok: true }) })

describe("AcademyStudentCrm connected owner", () => {
    it("loads students, opens detail and dispatches create/access/status actions", async () => { render(<AcademyStudentCrm siteId="site-1" />); await waitFor(() => expect(screen.getByTestId("state")).toHaveTextContent("answered")); fireEvent.click(screen.getByText("open")); await waitFor(() => expect(screen.getByTestId("state")).toHaveTextContent("answered:answered")); fireEvent.click(screen.getByText("name")); fireEvent.click(screen.getByText("email")); fireEvent.click(screen.getByText("password")); fireEvent.click(screen.getByText("create")); fireEvent.click(screen.getByText("course")); fireEvent.click(screen.getByText("ban")); fireEvent.click(screen.getByText("grant")); fireEvent.click(screen.getByText("revoke")); await waitFor(() => expect(m.calls.create).toHaveBeenCalledWith(expect.objectContaining({ siteId: "site-1", password: "secret" }))); expect(m.calls.status).toHaveBeenCalled(); expect(m.calls.grant).toHaveBeenCalled(); expect(m.calls.revoke).toHaveBeenCalled() })
    it("keeps refused list and failed detail distinct", async () => { m.calls.list.mockResolvedValue({ ok: false, data: undefined }); render(<AcademyStudentCrm siteId="site-1" />); await waitFor(() => expect(screen.getByTestId("state")).toHaveTextContent("refused:idle")); m.calls.detail.mockResolvedValue({ ok: false, data: undefined }); fireEvent.click(screen.getByText("open")); await waitFor(() => expect(screen.getByTestId("state")).toHaveTextContent("refused:refused")) })
})
