import { cn } from "@heroui/react";

/** Colocated CSS hooks owned by the public landing composition. */
export const CLASS_NAMES = {
  skipLink: cn("skip-link"),
  siteHeader: cn("site-header"),
  headerAction: cn("header-action"),
  hero_sectionShell: cn("hero", "section-shell"),
  heroVisual: cn("hero-visual"),
  heroArtwork: cn("hero-artwork"),
  graphNode: cn("graph-node"),
  srOnly: cn("sr-only"),
  eyebrow: cn("eyebrow"),
  heroLede: cn("hero-lede"),
  actions: cn("actions"),
  heroFlow: cn("hero-flow"),
  button: cn("button"),
  button_buttonGhost: cn("button", "button-ghost"),
  heroNote: cn("hero-note"),
  responsibilityMap: cn("responsibility-map"),
  mapTop: cn("map-top"),
  statusDot: cn("status-dot"),
  mapCenter: cn("map-center"),
  mapKicker: cn("map-kicker"),
  mapFlow: cn("map-flow"),
  mapProof: cn("map-proof"),
  problem: cn("problem"),
  sectionShell_split: cn("section-shell", "split"),
  sectionIndex: cn("section-index"),
  sectionShell_responsibility: cn("section-shell", "responsibility"),
  sectionHeading: cn("section-heading"),
  responsibilityGrid: cn("responsibility-grid"),
  loop: cn("loop"),
  sectionShell: cn("section-shell"),
  sectionHeading_light: cn("section-heading", "light"),
  loopTrack: cn("loop-track"),
  loopCaption: cn("loop-caption"),
  sectionShell_roles: cn("section-shell", "roles"),
  roleIntro: cn("role-intro"),
  roleRail: cn("role-rail"),
  roleGrid: cn("role-grid"),
  roleIcon: cn("role-icon"),
  intentSection: cn("intent-section"),
  intentGrid: cn("intent-grid"),
  intentTitle: cn("intent-title"),
  intentArtwork: cn("intent-artwork"),
  instancesTheatre: cn("instances-theatre"),
  sectionShell_instances: cn("section-shell", "instances"),
  instancesHeading: cn("instances-heading"),
  instanceStack: cn("instance-stack"),
  instanceTop: cn("instance-top"),
  instanceEvidence: cn("instance-evidence"),
  offer: cn("offer"),
  sectionShell_offerGrid: cn("section-shell", "offer-grid"),
  offerArtwork: cn("offer-artwork"),
  offerCopy: cn("offer-copy"),
  priceCard: cn("price-card"),
  price: cn("price"),
  cardNote: cn("card-note"),
  sectionShell_footerInner: cn("section-shell", "footer-inner"),
} as const;
