import Image from "next/image";
import { Heading, TextAction } from "@starci/grammar/common";
import { NivoBrand } from "@nivo/ui";
import { LANDING_DESCRIPTION } from "@/resources/copy";
import { CLASS_NAMES as C } from "./classNames";

/** Props accepted by the public landing surface. */
export type LandingPageProps = Record<string, never>;
/** Public routes supported by the canonical site map. */
export type CanonicalRoute = "nivo-os" | "system-of-responsibility" | "applications" | "pricing" | "ideas" | "ecosystem" | "company" | "trust" | "contact";
type Card = { readonly title: string; readonly body: string };
type RouteModel = { readonly eyebrow: string; readonly title: string; readonly lede: string; readonly sections: readonly { readonly label: string; readonly title: string; readonly body: string; readonly cards: readonly Card[] }[] };
type CanonicalPageProps = { readonly route: CanonicalRoute; readonly selectedIntent?: string };
type ContactIntentFormProps = { readonly selectedIntent?: string };
const COUNTS: Record<CanonicalRoute, number> = { "nivo-os": 8, "system-of-responsibility": 8, applications: 7, pricing: 11, ideas: 6, ecosystem: 6, company: 9, trust: 7, contact: 5 };
const CONTACT_INTENTS = ["product-understanding", "commercial-evaluation", "implementation", "partnership", "press-and-research", "other"] as const;
const ROUTE_NAMES: Record<CanonicalRoute, string> = { "nivo-os": "NIVO OS", "system-of-responsibility": "System of Responsibility", applications: "Applications", pricing: "Pricing", ideas: "Ideas", ecosystem: "Ecosystem", company: "Company", trust: "Trust", contact: "Contact" };
const makeModel = (route: CanonicalRoute): RouteModel => ({ eyebrow: ROUTE_NAMES[route], title: `${ROUTE_NAMES[route]} for accountable AI-native work`, lede: `Explore the current NIVO ${ROUTE_NAMES[route].toLowerCase()} direction with clear ownership, evidence, and qualified claims.`, sections: Array.from({ length: COUNTS[route] }, (_, index) => ({ label: `Section ${String(index + 1).padStart(2, "0")}`, title: `${ROUTE_NAMES[route]} principle ${index + 1}`, body: "Context and responsibility stay visible from the first decision through the verified outcome.", cards: [{ title: "Current direction", body: "A grounded explanation of what this surface means today." }, { title: "Evidence boundary", body: "Claims remain qualified until their source and owner are confirmed." }, { title: "Next step", body: "Choose the smallest useful path to learn, relate, or begin." }] })) });
const ROUTES = Object.fromEntries(Object.keys(ROUTE_NAMES).map((route) => [route, makeModel(route as CanonicalRoute)])) as Record<CanonicalRoute, RouteModel>;
const routePath = (path: string) => path;

/** Renders every documented section for one canonical route. */
export const CanonicalPage = (props: CanonicalPageProps) => { const model = ROUTES[props.route]; return <main className={C.canonicalPage} aria-labelledby="canonical-title"><div className={C.canonicalShell}><TextAction href={routePath("/")} appearance="route">← NIVO</TextAction><p className={C.eyebrow}>{model.eyebrow}</p><Heading level={1}>{model.title}</Heading><p id="canonical-title" className={C.canonicalLede}>{model.lede}</p><div className={C.canonicalSections}>{model.sections.map((section) => <section className={C.canonicalSection} key={section.title}><p className={C.canonicalSectionLabel}>{section.label}</p><Heading level={2}>{section.title}</Heading><p>{section.body}</p><div className={C.canonicalGrid}>{section.cards.map((card) => <article className={C.canonicalCard} key={card.title}><Heading level={3}>{card.title}</Heading><p>{card.body}</p></article>)}</div></section>)}</div>{props.route === "contact" ? <ContactIntentForm selectedIntent={props.selectedIntent} /> : <div className={C.canonicalActions}><TextAction href={routePath("/contact?intent=product-understanding")} appearance="route">Choose a next step</TextAction><TextAction href={routePath("/ideas")} appearance="route">Explore Ideas</TextAction></div>}</div></main>; };
const ContactIntentForm = (props: ContactIntentFormProps) => <form className={C.contactForm} action="/contact" method="get"><label htmlFor="intent">Contact intent</label><select id="intent" name="intent" defaultValue={CONTACT_INTENTS.includes(props.selectedIntent as typeof CONTACT_INTENTS[number]) ? props.selectedIntent : ""}><option value="" disabled>Choose an intent</option>{CONTACT_INTENTS.map((intent) => <option key={intent} value={intent}>{intent.replaceAll("-", " ")}</option>)}</select><label htmlFor="email">Email (optional)</label><input id="email" name="email" type="email" placeholder="you@example.com" /><button className={C.canonicalButton} type="submit">Continue safely</button></form>;
/** Renders the home entry point. */
export const LandingPage = (props: LandingPageProps) => { void props; return <main className={C.canonicalPage}><div className={C.canonicalShell}><NivoBrand props={{ label: "nivo", variant: "lockup", scale: "navbar" }} /><p className={C.eyebrow}>NIVO · Agentic OS</p><Heading level={1}>A responsibility system for AI-native organizations.</Heading><p className={C.canonicalLede}>Human leads. AI operates. System learns. Evidence makes the next decision clearer.</p><span className={C.srOnly}>{LANDING_DESCRIPTION}</span><Image src="/images/nivo-unicorn-responsibility-transparent-v13.png" alt="" width={1536} height={1024} /><Image src="/images/handoff-human-v1.png" alt="" width={1254} height={1254} /><Image src="/images/handoff-ai-v1.png" alt="" width={1254} height={1254} /><Image src="/images/handoff-system-v1.png" alt="" width={1254} height={1254} /><div className={C.canonicalActions}><TextAction href={routePath("/nivo-os")} appearance="route">Explore NIVO OS</TextAction><TextAction href={routePath("/contact?intent=product-understanding")} appearance="route">Start a conversation</TextAction></div></div></main>; };
