#!/usr/bin/env node
/**
 * scripts/sync-ports.mjs -- take every port this repo uses from the one registry that owns them.
 *
 *   npm run sync:ports            write the generated env, report anything that drifted
 *   npm run sync:ports -- --check report only, write nothing
 *
 * THERE IS ONE REGISTRY AND IT IS NOT HERE. `nivo-backend/metadata.json` declares
 * `portOffset` and resolves every host port as `basePorts[k] + portOffset`; it is what the backend,
 * its compose fragments and its env bridge already derive from. This repo consumes two of those
 * numbers -- the academy API it calls, and the dev ports its own apps listen on -- and the honest
 * thing is to READ them rather than to keep a second copy that agrees today.
 *
 * WHY NOT A `metadata.json` OF OUR OWN. Because a second registry is the drift, not the cure. The
 * numbers this repo consumes are decided by the project that publishes them; a local copy would
 * agree until the day somebody moves the offset, and then the failure is a landing page with an
 * empty catalog and no error anywhere -- `fetchCourses` turns an unreachable API into the same
 * empty state a brand-new academy has.
 *
 * WHAT IT WRITES, AND WHAT IT ONLY REPORTS. It writes `apps/expert/.env.local`, because a generated
 * file is the right home for a derived value. It does NOT rewrite `package.json` dev ports or the
 * fallback literal in `src/api/graphql.ts`: those are source somebody reads and edits, and a script
 * that silently rewrote them would make the disagreement invisible instead of fixed. They are
 * checked and named, which is the same bargain `nivo-backend`'s own `sync.mjs` makes with the keys
 * it cannot own.
 *
 * IN PRODUCTION THIS SCRIPT DOES NOT RUN. `NEXT_PUBLIC_ACADEMY_API_URL` is set by the deployment,
 * where the sibling checkout this reads does not exist. That is why the value travels as an env var
 * rather than as an import.
 */

import {
    existsSync, readFileSync, writeFileSync,
} from "node:fs"
import {
    dirname, join, resolve,
} from "node:path"
import {
    fileURLToPath,
} from "node:url"

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const REGISTRY = resolve(REPO_ROOT, "../nivo-backend/metadata.json")
const ENV_TARGET = join(REPO_ROOT, "apps/expert/.env.local")
const CLIENT = join(REPO_ROOT, "apps/expert/src/api/graphql.ts")

const MARKER = "# GENERATED by scripts/sync-ports.mjs -- do not edit by hand"

const ESC = String.fromCharCode(27)
const paint = (code, text) => (process.stdout.isTTY ? `${ESC}[${code}m${text}${ESC}[0m` : text)
const green = (text) => paint("32", text)
const yellow = (text) => paint("33", text)
const dim = (text) => paint("2", text)

/** Which app owns which `fixedPorts` entry. */
const DEV_PORTS = [
    { app: "apps/app", key: "webApp" },
    { app: "apps/expert", key: "webExpert" },
]

const die = (message, hints = []) => {
    console.error(`\nsync:ports: ${message}`)
    for (const hint of hints) {
        console.error(`  ${hint}`)
    }
    console.error("")
    process.exit(1)
}

if (!existsSync(REGISTRY)) {
    die(`no registry at ${REGISTRY}`, [
        "this repo derives its ports from the nivo-backend checkout beside it.",
        "in a deployment, set NEXT_PUBLIC_ACADEMY_API_URL instead of running this.",
    ])
}

let registry
try {
    registry = JSON.parse(readFileSync(REGISTRY, "utf8"))
} catch (error) {
    die(`the registry is not valid JSON: ${error.message}`)
}

const apiPort = registry.ports?.expertApi
if (typeof apiPort !== "number") {
    die("the registry declares no ports.expertApi", [
        "that is the academy API this app calls; nothing here can be derived without it",
    ])
}
const apiUrl = `http://localhost:${apiPort}/graphql`

const contents = [
    MARKER,
    "#",
    `#   source   ../nivo-backend/metadata.json  (ports.expertApi, offset +${registry.portOffset})`,
    "#   command  npm run sync:ports",
    "#",
    "# A deployment sets this itself; the registry beside this checkout is a developer convenience.",
    "",
    `NEXT_PUBLIC_ACADEMY_API_URL=${apiUrl}`,
    "",
].join("\n")

const check = process.argv.includes("--check")
if (check) {
    console.log(`\n${contents}`)
} else {
    writeFileSync(ENV_TARGET, contents)
    console.log(`\n${green("ok")}  wrote apps/expert/.env.local`)
}
console.log(dim(`    academy API -> ${apiUrl}`))

/* What the script cannot own, and therefore has to name. */
const drift = []

// The fallback in the client is a literal, and a literal is a second opinion the moment the
// registry moves. It stays a literal on purpose -- a fresh clone must render before any script has
// run -- so the cost of keeping it is this check.
if (existsSync(CLIENT)) {
    const source = readFileSync(CLIENT, "utf8")
    const fallback = source.match(/\?\?\s*"http:\/\/localhost:(\d+)\/graphql"/)
    if (!fallback) {
        drift.push("src/api/graphql.ts: could not find the fallback URL to check")
    } else if (Number(fallback[1]) !== apiPort) {
        drift.push(`src/api/graphql.ts: fallback is :${fallback[1]}, registry says :${apiPort}`)
    }
}

for (const { app, key } of DEV_PORTS) {
    const declared = registry.fixedPorts?.[key]
    const manifest = join(REPO_ROOT, app, "package.json")
    if (declared === undefined || !existsSync(manifest)) {
        continue
    }
    const dev = JSON.parse(readFileSync(manifest, "utf8")).scripts?.dev ?? ""
    const used = dev.match(/-p\s+(\d+)/)
    if (!used) {
        drift.push(`${app}: dev script names no port, registry says :${declared}`)
    } else if (Number(used[1]) !== declared) {
        drift.push(`${app}: dev is :${used[1]}, registry fixedPorts.${key} says :${declared}`)
    }
}

if (drift.length > 0) {
    console.log(`\n${yellow("drift")}  ${drift.length} place(s) this script does not own:`)
    for (const line of drift) {
        console.log(`         ${line}`)
    }
    console.log(dim("\n         edit them to match, or move the registry -- but not one without the other"))
} else {
    console.log(dim("    no drift: every port outside the generated file matches the registry"))
}
console.log("")
