/**
 * The one door a component uses to reach data.
 *
 * A component imports `@/hooks`, never `@/hooks/swr/...`: `@/hooks/swr` is the
 * internal transport folder, and this file is its only public face. Every line
 * below names one hook, so a reader can see the whole surface without opening a
 * second file and a spec can mock the door in one `vi.mock("@/hooks", ...)`.
 * Hooks only: cache keys, request modules, response types and the helpers that
 * read a transport answer stay behind their own paths — `nivoQueryReading`,
 * `nivoQueryPayload` and `NivoQueryAnswer` live in `@/modules/query`.
 */
export { useNivoQuery } from "./swr/useNivoQuery"
export { useNivoMutation } from "./swr/useNivoMutation"
export { useAccountingWorkbench } from "./agentos/useAccountingWorkbench"
export { useAccountingWorkbenchCommands } from "./agentos/useAccountingWorkbenchCommands"
export { useAccountingWorkbenchReads } from "./agentos/useAccountingWorkbenchReads"
export { useSalesWorkbench } from "./agentos/useSalesWorkbench"
export { useSalesWorkbenchCommands } from "./agentos/useSalesWorkbenchCommands"
export { useSalesWorkbenchReads } from "./agentos/useSalesWorkbenchReads"
export { useSalesDecision } from "./agentos/useSalesDecision"
export { useSalesHandoff } from "./agentos/useSalesHandoff"
export { useQueryNoticeData } from "./query/useQueryNoticeData"
export type { QueryNoticeDataOf } from "./query/useQueryNoticeData"
export { useAgentOSShell } from "./agentos/useAgentOSShell"
export { useModuleOperate } from "./agentos/useModuleOperate"
export { useModuleRuntime } from "./agentos/useModuleRuntime"
export { useModuleSettings } from "./agentos/useModuleSettings"
export { useModuleSetupSession } from "./agentos/useModuleSetupSession"
export { useModuleTestRun } from "./agentos/useModuleTestRun"
export { useAgentOSModuleStudioProjection } from "./agentos/useAgentOSModuleStudioProjection"
export { usePurchaseStatusActions } from "./agentos/usePurchaseStatusActions"
export { usePurchaseStatusPhase } from "./agentos/usePurchaseStatusPhase"
export { usePurchaseStatusQueries } from "./agentos/usePurchaseStatusQueries"
export { useAgentOSProvisioningActions } from "./provisioning/useAgentOSProvisioningActions"
export { useAgentOSProvisioningFlow } from "./provisioning/useAgentOSProvisioningFlow"
export { useAgentOSProvisioningPhase } from "./provisioning/useAgentOSProvisioningPhase"
export { useTemplateAppProvisioning } from "./provisioning/useTemplateAppProvisioning"
export type { TemplateAppProvisioningContext } from "./provisioning/useTemplateAppProvisioning"

export { useQueryAccountingEvidenceSwr } from "./swr/queries/useQueryAccountingEvidenceSwr"
export { useQueryAccountingResultDetailSwr } from "./swr/queries/useQueryAccountingResultDetailSwr"
export { useQueryAccountingRoutineResultSwr } from "./swr/queries/useQueryAccountingRoutineResultSwr"
export { useQueryAccountingSummarySwr } from "./swr/queries/useQueryAccountingSummarySwr"

export { useQuerySalesActionSwr } from "./swr/queries/useQuerySalesActionSwr"
export { useQuerySalesCommandSwr } from "./swr/queries/useQuerySalesCommandSwr"
export { useQuerySalesDecisionRequestSwr } from "./swr/queries/useQuerySalesDecisionRequestSwr"
export { useQuerySalesHandoffSwr } from "./swr/queries/useQuerySalesHandoffSwr"
export { useQuerySalesOpportunitySwr } from "./swr/queries/useQuerySalesOpportunitySwr"
export { useQuerySalesPipelineSwr } from "./swr/queries/useQuerySalesPipelineSwr"
export { useQuerySalesPolicySwr } from "./swr/queries/useQuerySalesPolicySwr"
export { useQuerySalesReadinessSwr } from "./swr/queries/useQuerySalesReadinessSwr"

export { useQueryCatalogItemsSwr } from "./swr/queries/useQueryCatalogItemsSwr"
export { useQueryMyAcademyGrowthSnapshotSwr } from "./swr/queries/useQueryMyAcademyGrowthSnapshotSwr"
export { useQueryMyAcademyIntegrationsSwr } from "./swr/queries/useQueryMyAcademyIntegrationsSwr"
export { useQueryMyAcademyStudentDetailSwr } from "./swr/queries/useQueryMyAcademyStudentDetailSwr"
export { useQueryMyAcademyStudentsSwr } from "./swr/queries/useQueryMyAcademyStudentsSwr"
export { useQueryMyAgentWorkspaceControlCenterSwr } from "./swr/queries/useQueryMyAgentWorkspaceControlCenterSwr"
export { useQueryMyAgentWorkspacesSwr } from "./swr/queries/useQueryMyAgentWorkspacesSwr"
export { useQueryMyAgentosAiKnowledgeReadinessSwr } from "./swr/queries/useQueryMyAgentosAiKnowledgeReadinessSwr"
export { useQueryMyAgentosCustomModuleStudioSwr } from "./swr/queries/useQueryMyAgentosCustomModuleStudioSwr"
export { useQueryMyAgentosModuleInstallationSwr } from "./swr/queries/useQueryMyAgentosModuleInstallationSwr"
export { useQueryMyAgentosModuleInstallationsSwr } from "./swr/queries/useQueryMyAgentosModuleInstallationsSwr"
export { useQueryMyAgentosModuleRuntimeSwr } from "./swr/queries/useQueryMyAgentosModuleRuntimeSwr"
export { useQueryMyAgentosModuleTestRunSwr } from "./swr/queries/useQueryMyAgentosModuleTestRunSwr"
export { useQueryMyAgentosModuleTestSurfaceSwr } from "./swr/queries/useQueryMyAgentosModuleTestSurfaceSwr"
export { useQueryMyAgentosSolutionModulesSwr } from "./swr/queries/useQueryMyAgentosSolutionModulesSwr"
export { useQueryMyCatalogOrdersSwr } from "./swr/queries/useQueryMyCatalogOrdersSwr"
export { useQueryMyDomainsSwr } from "./swr/queries/useQueryMyDomainsSwr"
export { useQueryMyExpertSiteDeploymentSwr } from "./swr/queries/useQueryMyExpertSiteDeploymentSwr"
export { useQueryMyExpertSiteLeadsSwr } from "./swr/queries/useQueryMyExpertSiteLeadsSwr"
export { useQueryMyExpertSitesSwr } from "./swr/queries/useQueryMyExpertSitesSwr"
export { useQueryMyInstancesSwr } from "./swr/queries/useQueryMyInstancesSwr"
export { useQueryMyInvoicesSwr } from "./swr/queries/useQueryMyInvoicesSwr"
export { useQueryMyPodOpenclawStatusSwr } from "./swr/queries/useQueryMyPodOpenclawStatusSwr"
export { useQueryMyWalletSwr } from "./swr/queries/useQueryMyWalletSwr"
export { useQueryMyWalletTransactionsSwr } from "./swr/queries/useQueryMyWalletTransactionsSwr"
export { useReadMyAgentosModuleTestRun } from "./swr/queries/useReadMyAgentosModuleTestRun"

export { useQueryChatbotWorkbenchSwr } from "./swr/queries/useQueryChatbotWorkbenchSwr"

export { useMutateAcademyIntegrationSwr } from "./swr/mutations/useMutateAcademyIntegrationSwr"
export { useMutateCreateAcademyStudentSwr } from "./swr/mutations/useMutateCreateAcademyStudentSwr"
export { useMutateDraftLeadReplySwr } from "./swr/mutations/useMutateDraftLeadReplySwr"
export { useMutateGrantAcademyCourseAccessSwr } from "./swr/mutations/useMutateGrantAcademyCourseAccessSwr"
export { useMutateRevokeAcademyCourseAccessSwr } from "./swr/mutations/useMutateRevokeAcademyCourseAccessSwr"
export { useMutateSetAcademyStudentStatusSwr } from "./swr/mutations/useMutateSetAcademyStudentStatusSwr"
export { useMutateUpdateExpertSiteLeadSwr } from "./swr/mutations/useMutateUpdateExpertSiteLeadSwr"

export { useMutateContinueBrokeredSignInSwr } from "./swr/mutations/useMutateContinueBrokeredSignInSwr"
export { useMutateForgotPasswordInitSwr } from "./swr/mutations/useMutateForgotPasswordInitSwr"
export { useMutateForgotPasswordResendSwr } from "./swr/mutations/useMutateForgotPasswordResendSwr"
export { useMutateForgotPasswordVerifyOtpSwr } from "./swr/mutations/useMutateForgotPasswordVerifyOtpSwr"
export { useMutateSignInSwr } from "./swr/mutations/useMutateSignInSwr"
export { useMutateSignOutSwr } from "./swr/mutations/useMutateSignOutSwr"
export { useMutateEndPrincipalSessionsSwr } from "./swr/mutations/useMutateEndPrincipalSessionsSwr"
export { useMutateVerifyTwoFactorSwr } from "./swr/mutations/useMutateVerifyTwoFactorSwr"
export { useMutateSignUpInitSwr } from "./swr/mutations/useMutateSignUpInitSwr"
export { useMutateSignUpResendSwr } from "./swr/mutations/useMutateSignUpResendSwr"
export { useMutateSignUpVerifyOtpSwr } from "./swr/mutations/useMutateSignUpVerifyOtpSwr"
export { useOauthReturnExchange } from "./swr/mutations/useOauthReturnExchange"

export { useMutateAccountingAdmitEvidenceSwr } from "./swr/mutations/useMutateAccountingAdmitEvidenceSwr"
export { useMutateAccountingCorrectSwr } from "./swr/mutations/useMutateAccountingCorrectSwr"
export { useMutateAccountingExceptionSwr } from "./swr/mutations/useMutateAccountingExceptionSwr"
export { useMutateAccountingRoutineSwr } from "./swr/mutations/useMutateAccountingRoutineSwr"

export { useMutateSalesClarifyCommandSwr } from "./swr/mutations/useMutateSalesClarifyCommandSwr"
export { useMutateSalesCloseSwr } from "./swr/mutations/useMutateSalesCloseSwr"
export { useMutateSalesConfigurePolicySwr } from "./swr/mutations/useMutateSalesConfigurePolicySwr"
export { useMutateSalesDecideProposalSwr } from "./swr/mutations/useMutateSalesDecideProposalSwr"
export { useMutateSalesPrepareHandoffSwr } from "./swr/mutations/useMutateSalesPrepareHandoffSwr"
export { useMutateSalesRecoverActionSwr } from "./swr/mutations/useMutateSalesRecoverActionSwr"
export { useMutateSalesSubmitCommandSwr } from "./swr/mutations/useMutateSalesSubmitCommandSwr"
export { useMutateSalesSubmitHandoffSwr } from "./swr/mutations/useMutateSalesSubmitHandoffSwr"

export { useMutateCreateWalletTopUpPayLinkSwr } from "./swr/mutations/useMutateCreateWalletTopUpPayLinkSwr"
export { useMutatePayInvoiceSwr } from "./swr/mutations/useMutatePayInvoiceSwr"

export { useMutateAgentosModuleAttachmentUploadSwr } from "./swr/mutations/useMutateAgentosModuleAttachmentUploadSwr"
export { useMutateAnswerAgentosCustomModuleIntakeSwr } from "./swr/mutations/useMutateAnswerAgentosCustomModuleIntakeSwr"
export { useMutateConfigureAgentWorkspaceChannelSwr } from "./swr/mutations/useMutateConfigureAgentWorkspaceChannelSwr"
export { useMutateCreateAndPublishExpertSiteSwr } from "./swr/mutations/useMutateCreateAndPublishExpertSiteSwr"
export { useMutateFinalizeAgentosModuleAttachmentSwr } from "./swr/mutations/useMutateFinalizeAgentosModuleAttachmentSwr"
export { useMutateInstallAgentosSolutionModuleSwr } from "./swr/mutations/useMutateInstallAgentosSolutionModuleSwr"
export { useMutateIssueAgentWorkspaceAppLaunchSwr } from "./swr/mutations/useMutateIssueAgentWorkspaceAppLaunchSwr"
export { useMutateManageAgentosModuleRuntimeSwr } from "./swr/mutations/useMutateManageAgentosModuleRuntimeSwr"
export { useMutateOrderAgentosSwr } from "./swr/mutations/useMutateOrderAgentosSwr"
export { useMutatePublishAgentosCustomModuleSwr } from "./swr/mutations/useMutatePublishAgentosCustomModuleSwr"
export { useMutateReindexAgentWorkspaceKnowledgeSwr } from "./swr/mutations/useMutateReindexAgentWorkspaceKnowledgeSwr"
export { useMutateRemoveAgentosModuleAttachmentSwr } from "./swr/mutations/useMutateRemoveAgentosModuleAttachmentSwr"
export { useMutateRemoveAgentosModuleIntegrationSecretSwr } from "./swr/mutations/useMutateRemoveAgentosModuleIntegrationSecretSwr"
export { useMutateRenewAgentWorkspaceAppLaunchSwr } from "./swr/mutations/useMutateRenewAgentWorkspaceAppLaunchSwr"
export { useMutateRevokeAgentWorkspaceAppLaunchSwr } from "./swr/mutations/useMutateRevokeAgentWorkspaceAppLaunchSwr"
export { useMutateRunAgentosAiReadinessTestSwr } from "./swr/mutations/useMutateRunAgentosAiReadinessTestSwr"
export { useMutateRunAgentosModuleTestSwr } from "./swr/mutations/useMutateRunAgentosModuleTestSwr"
export { useMutateSaveAgentosModuleIntegrationSecretSwr } from "./swr/mutations/useMutateSaveAgentosModuleIntegrationSecretSwr"
export { useMutateStartAgentosCustomModuleIntakeSwr } from "./swr/mutations/useMutateStartAgentosCustomModuleIntakeSwr"

export { useMutateBindChatbotChannelSwr } from "./swr/mutations/useMutateBindChatbotChannelSwr"
export { useMutateReconcileChatbotDeliverySwr } from "./swr/mutations/useMutateReconcileChatbotDeliverySwr"
export { useMutateResolveChatbotHandoffSwr } from "./swr/mutations/useMutateResolveChatbotHandoffSwr"
export { useMutateRetryWorkspaceProvisioningOrderSwr } from "./swr/mutations/useMutateRetryWorkspaceProvisioningOrderSwr"
export { useMutateSetChatbotHandoffSwr } from "./swr/mutations/useMutateSetChatbotHandoffSwr"
export { useMutateStartChatbotZaloOauthSwr } from "./swr/mutations/useMutateStartChatbotZaloOauthSwr"

export { useQueryWorkspaceCheckoutOffersSwr } from "./swr/queries/useQueryWorkspaceCheckoutOffersSwr"
export { useQueryWorkspaceCheckoutStatusSwr } from "./swr/queries/useQueryWorkspaceCheckoutStatusSwr"
export { useQueryWorkspaceCheckoutEntrySwr } from "./swr/queries/useQueryWorkspaceCheckoutEntrySwr"
export { useMutateWorkspaceCheckoutStartSwr } from "./swr/mutations/useMutateWorkspaceCheckoutStartSwr"
export { useMutateRecoverWorkspacePurchaseSwr } from "./swr/mutations/useMutateRecoverWorkspacePurchaseSwr"

export { useQueryCollabCommandsSwr } from "./swr/queries/useQueryCollabCommandsSwr"
export { useQueryCollabGroupSwr } from "./swr/queries/useQueryCollabGroupSwr"
export { useQueryCollabNoticeSwr } from "./swr/queries/useQueryCollabNoticeSwr"
export { useQueryCollabNoticesSwr } from "./swr/queries/useQueryCollabNoticesSwr"
export { useQueryCollabOfficeSwr } from "./swr/queries/useQueryCollabOfficeSwr"
export { useQueryCollabReconcileSwr } from "./swr/queries/useQueryCollabReconcileSwr"
export { useQueryCollabTaskSwr } from "./swr/queries/useQueryCollabTaskSwr"
export { useQueryCollabTasksSwr } from "./swr/queries/useQueryCollabTasksSwr"
export type { CollabTasksFilter } from "./swr/swr.shared"

export { useMutateCollabAcceptInvitationSwr } from "./swr/mutations/useMutateCollabAcceptInvitationSwr"
export { useMutateCollabInviteByEmailSwr } from "./swr/mutations/useMutateCollabInviteByEmailSwr"
export { useMutateCollabPostMessageSwr } from "./swr/mutations/useMutateCollabPostMessageSwr"
export { useMutateCollabPressApprovalSwr } from "./swr/mutations/useMutateCollabPressApprovalSwr"

export { useCollabLive } from "./collab-live/useCollabLive"
export { useCollabOfficeTransport } from "./collab-live/useCollabOfficeTransport"
export { useGroupChatTab } from "./collab/useGroupChatTab"
export { useGroupChatOffice } from "./collab/useGroupChatOffice"
export type { GroupChatOfficeScope } from "./collab/useGroupChatOffice"
export { useGroupChatTasks } from "./collab/useGroupChatTasks"
export type { GroupChatAnswering, GroupChatTasksScope } from "./collab/useGroupChatTasks"
export { useGroupChatComposer } from "./collab/useGroupChatComposer"
export type { GroupChatComposerScope } from "./collab/useGroupChatComposer"
export { useCompactMemberView } from "./collab/useCompactMemberView"
export type { CompactMemberView } from "./collab/useCompactMemberView"

export { default as useProvisioningRealtime } from "./realtime/useProvisioningRealtime"
export type { ProvisioningTarget, ProvisioningEvent, ProvisioningRealtimeState } from "./realtime/realtime.shared"

export { useAccessToken } from "./auth/useAccessToken"
export { useAccessTokenFrom } from "./auth/useAccessTokenFrom"
export { useLocaleFrom } from "./auth/useLocaleFrom"
export { useSession } from "./auth/useSession"
export { useAuthenticationCode } from "./auth/useAuthenticationCode"
export { useAuthenticationDetails } from "./auth/useAuthenticationDetails"
export { useAuthenticationNotice } from "./auth/useAuthenticationNotice"
export { useAuthenticationPhase } from "./auth/useAuthenticationPhase"
export { useAuthenticationTwoFactor } from "./auth/useAuthenticationTwoFactor"

export { usePathname } from "./i18n/usePathname"
export { useRouter } from "./i18n/useRouter"
export { useNow } from "./time/useNow"


export { useOverviewData } from "./overview/useOverviewData"
export { OverviewDataProvider } from "./overview/overview.shared"
export type { OverviewAnswer, OverviewDataProviderData, OverviewDataProviderProps } from "./overview/overview.shared"
export { usePersistedFlag } from "./session/usePersistedFlag"
