/** Responsive card-grid compositions used by the commercial routes. */
const VARIANTS = {
    base: "min-w-0",
    today: "grid grid-cols-4 gap-px mt-[clamp(2.5rem,5vw,5rem)] overflow-hidden rounded-3xl border border-[var(--landing-commercial-line)] bg-[var(--landing-commercial-line)] max-lg:grid-cols-2 max-[48.01rem]:grid-cols-1",
    philosophy:
        "grid grid-cols-3 gap-4 mt-16 [&>article]:grid [&>article]:min-h-[20rem] [&>article]:content-end [&>article]:gap-4 [&>article]:rounded-3xl [&>article]:border [&>article]:border-[var(--landing-commercial-panel-line)] [&>article]:bg-[var(--landing-commercial-panel-fill)] [&>article]:p-8 [&>article:nth-child(2)]:translate-y-8 [&>article:nth-child(2)]:bg-[var(--landing-commercial-accent-panel)] [&_p]:leading-[1.6] [&_p]:text-[var(--landing-inverse-muted)] [@media(max-width:64rem)]:grid-cols-1 [@media(max-width:64rem)]:[&>article]:min-h-56 [@media(max-width:64rem)]:[&>article:nth-child(2)]:translate-y-0",
    values:
        "grid grid-cols-6 gap-4 mt-16 [&>article]:col-span-2 [&>article]:grid [&>article]:min-h-[17rem] [&>article]:content-start [&>article]:gap-4 [&>article]:rounded-[1.35rem] [&>article]:border [&>article]:border-[var(--landing-commercial-line)] [&>article]:p-7 [&>article:nth-child(-n+2)]:col-span-3 [&>article:nth-child(-n+2)]:min-h-[15rem] [&>article:nth-child(3)]:bg-[var(--landing-commercial-ink)] [&>article:nth-child(3)]:text-[var(--landing-commercial-white)] [&_p]:leading-[1.55] [&>article>span:last-child]:justify-self-start [&>article>span:last-child]:self-end [@media(max-width:48rem)]:grid-cols-1 [@media(max-width:48rem)]:[&>article]:col-auto [@media(max-width:48rem)]:[&>article]:min-h-[13rem] [@media(max-width:48rem)]:[&>article:nth-child(-n+2)]:col-auto [@media(max-width:48rem)]:[&>article:nth-child(-n+2)]:min-h-[13rem]",
    intent:
        "w-full [&_[data-grammar-field-control='true']]:gap-3 [&_[data-grammar-option='true']]:w-[calc(50%-0.5rem)] [&_[data-grammar-option='true']]:relative [&_[data-grammar-option='true']]:grid [&_[data-grammar-option='true']]:min-h-[10.5rem] [&_[data-grammar-option='true']]:content-start [&_[data-grammar-option='true']]:gap-[0.8rem] [&_[data-grammar-option='true']]:overflow-hidden [&_[data-grammar-option='true']]:rounded-[1.25rem] [&_[data-grammar-option='true']]:border [&_[data-grammar-option='true']]:border-[var(--landing-commercial-line)] [&_[data-grammar-option='true']]:bg-[var(--landing-commercial-white)] [&_[data-grammar-option='true']]:p-[1.35rem] [&_[data-grammar-option='true']]:transition-[border-color,transform,box-shadow] [&_[data-grammar-option='true']]:duration-[180ms] [&_[data-grammar-option='true']]:ease-in-out [&_[data-grammar-option='true']]:cursor-pointer [&_[data-grammar-option='true']:hover]:-translate-y-[0.2rem] [&_[data-grammar-option='true']:hover]:border-[var(--accent)] [&_[data-grammar-option='true']:hover]:shadow-[var(--landing-commercial-contact-hover-shadow)] [&_[data-grammar-option='true']:focus-visible]:border-[var(--accent)] [&_[data-grammar-option='true']:focus-visible]:shadow-[var(--landing-commercial-contact-hover-shadow)] [&_[data-grammar-option='true'][data-selected='true']]:border-[var(--accent)] [&_[data-grammar-option='true'][data-selected='true']]:bg-[var(--landing-commercial-card-rose)] [&_[data-grammar-option='true'][data-selected='true']]:shadow-[inset_0_0_0_1px_var(--accent)] [&_[data-grammar-choice-target='true']]:grid [&_[data-grammar-choice-target='true']]:grid-cols-[1fr_auto] [&_[data-grammar-choice-target='true']]:gap-[0.8rem] [&_[data-grammar-choice-control='radio']]:absolute [&_[data-grammar-choice-control='radio']]:h-px [&_[data-grammar-choice-control='radio']]:w-px [&_[data-grammar-choice-control='radio']]:opacity-0 [&_[data-grammar-option='true'][data-selected='true']_[data-contact-intent-check]]:border-[var(--accent)] [&_[data-grammar-option='true'][data-selected='true']_[data-contact-intent-check]]:bg-[var(--accent)] [&_[data-grammar-option='true'][data-selected='true']_[data-contact-intent-check]]:text-[var(--landing-commercial-white)] [@media(max-width:48rem)]:[&_[data-grammar-option='true']]:w-full [@media(max-width:48rem)]:[&_[data-grammar-option='true']]:min-h-[9.5rem]",
} as const

/** Colocated grid utilities and card-layout variants. */
export const CLASS_NAMES = {
    ...VARIANTS,
    root: (variant: Exclude<keyof typeof VARIANTS, "base">, className?: string) =>
        `${VARIANTS.base} ${VARIANTS[variant]} ${className ?? ""}`.trim(),
} as const
