/** Localized, plain-string copy for the installed Chatbot workbench. */
export type ChatbotWorkbenchBlockBaseCopy = {
    readonly title: string
    readonly installation: string
    readonly channels: string
    readonly noChannels: string
    readonly connectZalo: string
    readonly conversations: string
    readonly openConversations: string
    readonly closeConversations: string
    readonly noConversations: string
    readonly selectConversation: string
    readonly selected: string
    readonly automated: string
    readonly handoffPending: string
    readonly humanOwned: string
    readonly returnPending: string
    readonly requestHandoff: string
    readonly resolveHandoff: string
    readonly messages: string
    readonly noMessages: string
    readonly pending: string
    readonly refused: string
    readonly actionRefused: string
    readonly permissionDenied: string
    readonly ambiguous: string
    readonly markDelivered: string
    readonly markFailed: string
    readonly recorded: string
    readonly deliveryQueued: string
    readonly deliveryPossibleStart: string
    readonly providerAccepted: string
    readonly delivered: string
    readonly read: string
    readonly deliveryUnknown: string
    readonly terminalNotDelivered: string
    readonly failedBeforeStart: string
    readonly cancelled: string
}
