import type { ReactNode } from "react";
import { Badge, Button, EmptyNotice, Heading, Input, PrimaryRailLayout, SectionHeader, SurfaceCard, SurfaceListCard, Text } from "@starci/grammar/common";
import type { useAccountingWorkbench, AccountingNotice } from "./useAccountingWorkbench";
import { ACCOUNTING_ACTION_ROW_CLASS_NAME, ACCOUNTING_FIELD_STACK_CLASS_NAME, ACCOUNTING_ROW_CLASS_NAME, ACCOUNTING_WORKBENCH_CLASS_NAME } from "./classNames";

const canonicalPeriod = /^\d{4}-(0[1-9]|1[0-2])-01$/;
const signedMinor = /^-?\d+$/;
const unsignedMinor = /^\d+$/;
type ChildrenProps = { readonly children: ReactNode };
type StatusNoticeProps = { readonly notice: AccountingNotice | null };
/** Settled data and interactions projected by the connected Accounting owner. */
export type AccountingWorkbenchBlockProps = { readonly view: ReturnType<typeof useAccountingWorkbench> };
const StatusNotice = ({ notice }: StatusNoticeProps) => notice === null ? null : <SurfaceCard><Text live="polite" tone={notice.kind === "success" ? "accent" : "default"}>{notice.message}</Text></SurfaceCard>;
const FieldStack = ({ children }: ChildrenProps) => <div className={ACCOUNTING_FIELD_STACK_CLASS_NAME} data-contract="GAP-4">{children}</div>;
const Row = ({ children }: ChildrenProps) => <div className={ACCOUNTING_ROW_CLASS_NAME} data-contract="GAP-2 PADDING-4">{children}</div>;
const ActionRow = ({ children }: ChildrenProps) => <div className={ACCOUNTING_ACTION_ROW_CLASS_NAME} data-contract="GAP-2">{children}</div>;

/** Render the complete responsive Accounting workbench from a settled controller view. */
export const AccountingWorkbenchBlockBase = (props: AccountingWorkbenchBlockProps) => {
  const { view } = props;
  const { t, currency, setCurrency, asOfDraft, setAsOfDraft, ledgerVersion, setLedgerVersion, notice, approverId, setApproverId, fileName, setFileName, mimeType, setMimeType, contentBase64, setContentBase64, classification, setClassification, documentAmount, setDocumentAmount, documentPeriod, setDocumentPeriod, sourceAmount, setSourceAmount, closePeriod, setClosePeriod, sourceEntryId, setSourceEntryId, effectivePeriod, setEffectivePeriod, deltaAmount, setDeltaAmount, correctionReason, setCorrectionReason, workbench, context, initialize, ingest, submitDocument, approveDocument, postDocument, reconcile, close, submitCorrection, approveCorrection, answer, model, role, isAsOf, correctionSubmitAllowed, correctionApproveAllowed, pendingCorrections, onInitialize, onIngest, onReconcile, onClose, onCorrection, documentCommand, approvePendingCorrection } = view;
  const primary = <FieldStack>
    <SectionHeader level={2} title={t("title")} description={t("description")} />
    <SurfaceCard label={t("statementSnapshot")} fact={model === undefined ? undefined : t("ledgerVersion", { version: model.ledgerVersion })}>
      <FieldStack>
        <ActionRow><Badge tone={isAsOf ? "warning" : "neutral"}>{isAsOf ? t("asOfMode", { version: ledgerVersion }) : t("currentMode")}</Badge>{role === undefined ? null : <Badge tone="neutral">{t(`role.${role}`)}</Badge>}</ActionRow>
        <Input id="accounting-currency" name="accounting-currency" label={t("currency")} value={currency} onValueChange={setCurrency} isRequired />
        <Input id="accounting-ledger-version" name="accounting-ledger-version" label={t("asOfVersion")} hint={t("asOfHint")} value={asOfDraft} onValueChange={setAsOfDraft} />
        <ActionRow><Button variant="secondary" isDisabled={asOfDraft.length === 0 || !unsignedMinor.test(asOfDraft)} onPress={() => setLedgerVersion(asOfDraft)}>{t("viewAsOf")}</Button><Button variant="ghost" isDisabled={!isAsOf} onPress={() => { setLedgerVersion(undefined); setAsOfDraft(""); }}>{t("returnCurrent")}</Button></ActionRow>
        {isAsOf ? <Text tone="accent" live="polite">{t("historicalAdvisory")}</Text> : null}
        <Heading level={3}>{model === undefined ? t("loadingAmount") : t("minorBalance", { amount: model.ledgerAmountMinor, currency: model.currency })}</Heading>
      </FieldStack>
    </SurfaceCard>
    {workbench.error !== undefined ? <EmptyNotice message={t("transportError")} description={t("nothingChanged")} actionLabel={t("retry")} onAction={() => void workbench.mutate()} /> : answer?.ok === false ? <EmptyNotice message={t("readRefused", { reason: answer.reason })} description={t("nothingChanged")} actionLabel={t("retry")} onAction={() => void workbench.mutate()} /> : null}
    <SurfaceListCard label={t("ledger")} fact={model === undefined ? undefined : t("rowCount", { count: model.ledger.length })} isLoading={answer === undefined && workbench.error === undefined}>
      {model?.ledger.length === 0 ? <EmptyNotice message={t("emptyLedger")} description={t("emptyLedgerHint")} /> : model?.ledger.map(entry => <Row key={entry.id}><ActionRow><Text weight="semibold">{t("minorAmount", { amount: entry.signedAmountMinor, currency: entry.currency })}</Text><Badge tone={entry.kind === "correction" ? "warning" : "neutral"}>{entry.kind}</Badge></ActionRow><Text size="sm">{entry.periodKey} · {t("ledgerVersion", { version: entry.ledgerVersion })}</Text><Text size="xs" tone="muted">{entry.reason ?? entry.id}</Text></Row>)}
    </SurfaceListCard>
    <SurfaceListCard label={t("documents")} fact={model === undefined ? undefined : t("rowCount", { count: model.documents.length })} isLoading={answer === undefined && workbench.error === undefined}>
      {model?.documents.length === 0 ? <EmptyNotice message={t("emptyDocuments")} description={t("emptyDocumentsHint")} /> : model?.documents.map(document => <Row key={document.id}><ActionRow><Text weight="semibold">{document.fileName}</Text><Badge tone={document.status === "posted" ? "success" : "neutral"}>{document.status}</Badge></ActionRow><Text size="sm">{document.periodKey} · {t("minorAmount", { amount: document.amountMinor, currency: document.currency })}</Text><ActionRow>{document.status === "ingested" && role === "owner" ? <Button size="sm" variant="secondary" isPending={submitDocument.isMutating} onPress={() => documentCommand("submit", document.id)}>{t("submitDocument")}</Button> : null}{document.status === "submitted" && role === "approver" ? <Button size="sm" variant="secondary" isPending={approveDocument.isMutating} onPress={() => documentCommand("approve", document.id)}>{t("approveDocument")}</Button> : null}{document.status === "approved" && role === "owner" ? <Button size="sm" variant="primary" isPending={postDocument.isMutating} onPress={() => documentCommand("post", document.id)}>{t("postDocument")}</Button> : null}</ActionRow></Row>)}
    </SurfaceListCard>
    <SurfaceCard label={t("documentIntake")}><form onSubmit={onIngest}><FieldStack><Input id="accounting-file-name" name="accounting-file-name" label={t("fileName")} value={fileName} onValueChange={setFileName} isRequired /><Input id="accounting-mime-type" name="accounting-mime-type" label={t("mimeType")} value={mimeType} onValueChange={setMimeType} isRequired /><Input id="accounting-content" name="accounting-content" label={t("contentBase64")} hint={t("contentHint")} value={contentBase64} onValueChange={setContentBase64} isRequired /><Input id="accounting-classification" name="accounting-classification" label={t("classification")} hint={t("classificationHint")} value={classification} onValueChange={setClassification} isRequired /><Input id="accounting-document-amount" name="accounting-document-amount" label={t("unsignedMinorAmount")} value={documentAmount} onValueChange={setDocumentAmount} isRequired isError={documentAmount.length > 0 && !unsignedMinor.test(documentAmount)} /><Input id="accounting-document-period" name="accounting-document-period" label={t("periodKey")} hint={t("periodHint")} value={documentPeriod} onValueChange={setDocumentPeriod} isRequired isError={documentPeriod.length > 0 && !canonicalPeriod.test(documentPeriod)} /><Button type="submit" variant="primary" isPending={ingest.isMutating} isDisabled={!unsignedMinor.test(documentAmount) || !canonicalPeriod.test(documentPeriod) || fileName.length === 0 || contentBase64.length === 0}>{t("addDocument")}</Button></FieldStack></form></SurfaceCard>
    <SurfaceCard label={t("reconciliationAndClose")}><FieldStack><form onSubmit={onReconcile}><FieldStack><Input id="accounting-source-amount" name="accounting-source-amount" label={t("signedSourceAmount")} hint={t("signedHint")} value={sourceAmount} onValueChange={setSourceAmount} isRequired isError={sourceAmount.length > 0 && !signedMinor.test(sourceAmount)} /><Button type="submit" variant="secondary" isPending={reconcile.isMutating} isDisabled={!signedMinor.test(sourceAmount)}>{t("reconcile")}</Button></FieldStack></form><form onSubmit={onClose}><FieldStack><Input id="accounting-close-period" name="accounting-close-period" label={t("closePeriod")} hint={t("periodHint")} value={closePeriod} onValueChange={setClosePeriod} isRequired isError={closePeriod.length > 0 && !canonicalPeriod.test(closePeriod)} /><Button type="submit" variant="secondary" isPending={close.isMutating} isDisabled={!canonicalPeriod.test(closePeriod)}>{t("closePeriodAction")}</Button></FieldStack></form></FieldStack></SurfaceCard>
  </FieldStack>;
  const rail = <FieldStack>
    <SurfaceCard label={t("appliedContext")} fact={context.data?.ok === true ? context.data.data.versionId : undefined}>{context.error !== undefined ? <Text live="polite">{t("transportError")}</Text> : context.data?.ok === false ? <Text live="polite">{t("readRefused", { reason: context.data.reason })}</Text> : <Text size="sm" tone="muted" isSkeleton={context.data === undefined}>{context.data?.ok === true ? context.data.data.digest : t("loadingContext")}</Text>}</SurfaceCard>
    <SurfaceListCard label={t("pendingCorrections")} fact={t("rowCount", { count: pendingCorrections.length })} isLoading={answer === undefined && workbench.error === undefined}>
      {model !== undefined && pendingCorrections.length === 0 ? <EmptyNotice message={t("emptyCorrections")} description={t("emptyCorrectionsHint")} /> : pendingCorrections.map(correction => <Row key={correction.id}><ActionRow><Text weight="semibold">{t("minorAmount", { amount: correction.signedDeltaMinor, currency: correction.currency })}</Text><Badge tone="warning">{t("pending")}</Badge></ActionRow><Text size="sm">{correction.effectivePeriodKey}</Text><Text size="xs" tone="muted">{correction.reason}</Text>{correctionApproveAllowed ? <Button size="sm" variant="primary" isPending={approveCorrection.isMutating} onPress={() => approvePendingCorrection(correction.id)}>{t("approveCorrection")}</Button> : <Text size="xs" tone="muted">{t("distinctApproverOnly")}</Text>}</Row>)}
    </SurfaceListCard>
    <SurfaceCard label={t("proposeCorrection")}><form onSubmit={onCorrection}><FieldStack><Input id="accounting-source-entry" name="accounting-source-entry" label={t("sourceEntry")} value={sourceEntryId} onValueChange={setSourceEntryId} isRequired /><Input id="accounting-effective-period" name="accounting-effective-period" label={t("effectivePeriod")} hint={t("periodHint")} value={effectivePeriod} onValueChange={setEffectivePeriod} isRequired isError={effectivePeriod.length > 0 && !canonicalPeriod.test(effectivePeriod)} /><Input id="accounting-delta" name="accounting-delta" label={t("signedDelta")} hint={t("signedHint")} value={deltaAmount} onValueChange={setDeltaAmount} isRequired isError={deltaAmount.length > 0 && (!signedMinor.test(deltaAmount) || deltaAmount === "0")} /><Input id="accounting-reason" name="accounting-reason" label={t("reason")} value={correctionReason} onValueChange={setCorrectionReason} isRequired /><Text size="xs" tone="muted">{model?.capabilities.reason ?? t("advisoryCapabilities")}</Text>{!correctionSubmitAllowed ? <Text size="xs" tone="accent" live="polite">{isAsOf ? t("historicalAdvisory") : t("permissionDenied")}</Text> : null}<Button type="submit" variant="primary" isPending={submitCorrection.isMutating} isDisabled={!correctionSubmitAllowed || sourceEntryId.length === 0 || correctionReason.length === 0 || !canonicalPeriod.test(effectivePeriod) || !signedMinor.test(deltaAmount) || deltaAmount === "0"}>{t("submitCorrection")}</Button></FieldStack></form></SurfaceCard>
    <SurfaceCard label={t("initialize")}><form onSubmit={onInitialize}><FieldStack><Input id="accounting-approver" name="accounting-approver" label={t("approverId")} hint={t("approverHint")} value={approverId} onValueChange={setApproverId} isRequired /><Button type="submit" variant="secondary" isPending={initialize.isMutating} isDisabled={approverId.length === 0}>{t("initializeAction")}</Button></FieldStack></form></SurfaceCard>
  </FieldStack>;
  return <div className={ACCOUNTING_WORKBENCH_CLASS_NAME} data-contract="GAP-5 MEASURE-2"><StatusNotice notice={notice} /><PrimaryRailLayout primary={primary} rail={rail} railWidth="standard" align="start" collapsedOrder="primary-first" /></div>;
};
