import { cn } from "@heroui/react"

/** Utility roles for the homepage sections, held at their page boundary. */
export const CLASS_NAMES = {
    inlineRoute: cn(
        "inline-flex",
        "flex-wrap",
        "items-center",
        "gap-[0.3em]",
        "[&>span]:inline-flex",
        "[&>span]:items-center",
        "[&>span]:gap-[0.3em]",
        "[&>span>span[aria-hidden=true]]:inline-flex",
        "[&>span>span[aria-hidden=true]]:text-landing-accent-bright",
        "[&_svg]:size-[0.82em]",
    ),
    hero: {
        section: cn(
            "relative",
            "isolate",
            "overflow-clip",
            "border-b",
            "border-separator",
            "bg-surface",
            "before:absolute",
            "before:inset-0",
            "before:-z-10",
            "before:left-[58%]",
            "before:bg-landing-surface-tint",
            "before:opacity-[0.7]",
            "before:content-['']",
            "before:[clip-path:ellipse(64%_78%_at_100%_24%)]",
        ),
        container: cn(
            "grid",
            "min-h-[min(50rem,calc(100dvh-var(--landing-header-height)))]",
            "grid-cols-home-hero",
            "items-center",
            "gap-home-hero-grid",
            "py-home-hero",
            "[@media(max-width:64rem)]:grid-cols-1",
            "[@media(max-width:64rem)]:gap-8",
            "[@media(max-width:48rem)]:min-h-auto",
            "[@media(max-width:48rem)]:pt-14",
            "[@media(max-width:48rem)]:pb-8",
        ),
        visual: cn(
            "relative",
            "min-w-0",
            "m-0",
            "[perspective:70rem]",
            "[@media(max-width:64rem)]:w-full",
            "[@media(max-width:64rem)]:max-w-home-visual",
            "[@media(max-width:64rem)]:justify-self-center",
            "[@media(max-width:48rem)]:w-[calc(100%+1.5rem)]",
            "[@media(max-width:48rem)]:-mx-3",
        ),
        titleAccent: cn("text-accent", "forced-colors:text-[Highlight]"),
        screenReaderOnly: "sr-only",
        actions: cn(
            "mt-3",
            "flex",
            "flex-wrap",
            "items-center",
            "gap-3",
            "[&>a]:min-h-11",
            "[&>button]:min-h-11",
            "[@media(max-width:48rem)]:w-full",
            "[@media(max-width:48rem)]:flex-col",
            "[@media(max-width:48rem)]:items-stretch",
            "[@media(max-width:48rem)]:[&>a]:w-full",
            "[@media(max-width:48rem)]:[&>a]:justify-center",
            "[@media(max-width:48rem)]:[&>button]:w-full",
            "[@media(max-width:48rem)]:[&>button]:justify-center",
        ),
        signal: cn(
            "absolute",
            "top-[14%]",
            "-right-2",
            "z-[3]",
            "inline-flex",
            "items-center",
            "gap-2",
            "rounded-full",
            "bg-landing-home-signal",
            "px-3.5",
            "py-[0.6rem]",
            "text-landing-accent-ink",
            "text-home-micro",
            "font-bold",
            "tracking-home-eyebrow",
            "uppercase",
            "shadow-landing-home-signal",
            "backdrop-blur-xl",
            "-rotate-2",
            "before:size-[0.45rem]",
            "before:shrink-0",
            "before:rounded-full",
            "before:bg-accent",
            "before:shadow-landing-home-signal-ring",
            "before:content-['']",
        ),
        mascot: cn(
            "relative",
            "z-[2]",
            "block",
            "h-auto",
            "w-[108%]",
            "max-w-none",
            "translate-y-[1%]",
            "drop-shadow-landing-home-mascot",
            "[@media(max-width:48rem)]:w-[125%]",
        ),
    },
    relevance: {
        section: cn(
            "relative",
            "isolate",
            "overflow-clip",
            "bg-landing-home-relevance",
            "bg-center",
            "bg-cover",
            "bg-no-repeat",
            "text-surface",
            "landing-inverse-band",
            "py-home-section",
            "forced-colors:bg-[Canvas]",
            "forced-colors:text-[CanvasText]",
        ),
        today: cn(
            "mt-10",
            "grid",
            "grid-cols-home-today",
            "items-center",
            "gap-x-12",
            "gap-y-6",
            "rounded-2xl",
            "bg-landing-home-today",
            "p-6",
            "shadow-landing-home-today",
            "backdrop-blur-[14px]",
            "[@media(max-width:64rem)]:grid-cols-1",
        ),
        todayGroup: cn(
            "grid",
            "gap-[0.45rem]",
            "[&>[data-component=Text]:first-child]:text-landing-accent-bright",
            "[&>[data-component=Text]:first-child]:tracking-home-kicker",
            "[&>[data-component=Text]:first-child]:uppercase",
            "[&>[data-component=Heading]]:text-surface",
            "[&>[data-component=Text]:not(:first-child)]:text-surface",
        ),
        todayPrinciple: cn(
            "[&>[data-component=Text]]:m-0",
            "[&>[data-component=Text]]:text-landing-accent-bright",
            "[&>[data-component=Text]]:tracking-home-kicker",
            "[&>[data-component=Text]]:uppercase",
        ),
        relevanceBody: cn(
            "mt-home-relevance-top",
            "grid",
            "grid-cols-home-relevance",
            "items-end",
            "gap-home-relevance-grid",
            "[@media(max-width:64rem)]:grid-cols-1",
        ),
        example: cn(
            "flex",
            "flex-col",
            "items-start",
            "gap-4",
            "border-l-2",
            "border-accent",
            "pl-6",
            "[&>[data-component=Text]:first-child]:text-landing-inverse-muted",
            "[&>[data-component=Text]:first-child]:tracking-home-eyebrow",
            "[&>[data-component=Text]:first-child]:uppercase",
            "[&>[data-component=Heading]]:text-surface",
            "[&>[data-component=Text]:nth-of-type(2)]:text-landing-inverse-muted",
            "[&>[data-component=Text]:nth-of-type(2)]:leading-home-copy",
            "[&>a[data-component=Button]]:min-h-11",
        ),
    },
    operatingModel: {
        section: cn("border-b", "border-landing-home-separator", "bg-surface", "py-home-section"),
        label: cn(
            "[&>[data-component=Text]]:tracking-home-eyebrow",
            "[&>[data-component=Text]]:uppercase",
        ),
        visuals: cn(
            "mt-home-relevance-top",
            "grid",
            "grid-cols-4",
            "gap-home-visuals",
            "[@media(max-width:64rem)]:grid-cols-2",
            "[@media(max-width:40rem)]:[&[aria-label]]:grid-cols-1",
            "[@media(max-width:40rem)]:gap-4",
            "[@media(max-width:40rem)]:[&>figure]:grid-cols-home-role-card-mobile",
            "[@media(max-width:40rem)]:[&>figure]:grid-rows-[auto]",
            "[@media(max-width:40rem)]:[&>figure]:items-stretch",
        ),
        visualMedia: cn(
            "relative",
            "aspect-square",
            "flex",
            "items-end",
            "justify-center",
            "overflow-hidden",
            "rounded-landing-home-surface",
            "bg-landing-surface-tint",
            "px-[0.65rem]",
            "pt-[0.65rem]",
            "after:absolute",
            "after:right-[10%]",
            "after:bottom-[6%]",
            "after:left-[10%]",
            "after:h-[8%]",
            "after:rounded-full",
            "after:bg-landing-home-visual-floor",
            "after:blur-[0.8rem]",
            "after:content-['']",
        ),
        visualCaption: cn(
            "grid",
            "min-h-home-caption",
            "content-start",
            "gap-[0.55rem]",
            "bg-transparent",
            "px-[1.2rem]",
            "pt-[1.15rem]",
            "pb-[1.35rem]",
            "[&>*]:m-0",
            "[&>p:first-child]:tracking-home-eyebrow",
            "[@media(max-width:40rem)]:min-h-home-caption-mobile",
            "[@media(max-width:40rem)]:content-center",
        ),
        footer: cn(
            "mt-12",
            "grid",
            "grid-cols-home-operating-footer",
            "items-center",
            "gap-8",
            "rounded-[1.25rem]",
            "bg-landing-surface-tint",
            "px-6",
            "py-[1.35rem]",
            "shadow-landing-home-visual",
            "[@media(max-width:64rem)]:grid-cols-1",
        ),
        principle: cn(
            "flex",
            "min-w-0",
            "items-baseline",
            "gap-4",
            "border-r",
            "border-border",
            "pr-8",
            "[@media(max-width:64rem)]:pr-0",
            "[@media(max-width:64rem)]:pb-5",
            "[@media(max-width:64rem)]:border-r-0",
            "[@media(max-width:64rem)]:border-b",
            "[@media(max-width:64rem)]:border-landing-home-separator",
            "[@media(max-width:48rem)]:w-full",
            "[@media(max-width:48rem)]:items-start",
            "[@media(max-width:48rem)]:flex-col",
        ),
        actions: cn(
            "flex",
            "flex-wrap",
            "items-center",
            "justify-end",
            "gap-3",
            "[&>a]:min-h-11",
            "[@media(max-width:64rem)]:justify-start",
            "[@media(max-width:48rem)]:w-full",
            "[@media(max-width:48rem)]:flex-col",
            "[@media(max-width:48rem)]:items-stretch",
            "[@media(max-width:48rem)]:[&>a]:w-full",
        ),
    },
    commercial: {
        section: cn(
            "relative",
            "isolate",
            "overflow-clip",
            "bg-landing-surface-tint",
            "py-home-section",
            "forced-colors:bg-[Canvas]",
            "forced-colors:text-[CanvasText]",
        ),
        container: cn(
            "grid",
            "grid-cols-home-commercial",
            "items-center",
            "gap-home-relevance-grid",
            "[@media(max-width:64rem)]:grid-cols-1",
        ),
        copy: cn("grid", "gap-8", "[&_.starci-core-section-header]:gap-4"),
        actions: cn(
            "flex",
            "flex-wrap",
            "items-center",
            "gap-3",
            "[&>a]:min-h-11",
            "[@media(max-width:48rem)]:w-full",
            "[@media(max-width:48rem)]:flex-col",
            "[@media(max-width:48rem)]:items-stretch",
            "[@media(max-width:48rem)]:[&>a]:w-full",
        ),
        route: cn(
            "relative",
            "grid",
            "grid-cols-3",
            "w-full",
            "max-w-[var(--container-home-route)]",
            "justify-self-center",
            "items-start",
            "gap-home-route",
            "min-h-[25rem]",
            "rounded-[3.5rem]",
            "bg-landing-home-commercial-route-surface",
            "bg-landing-home-commercial-route",
            "shadow-landing-home-commercial-route",
            "px-home-route-padding-x",
            "py-home-route-padding-y",
            "[@media(max-width:48rem)]:grid-cols-1",
            "[@media(max-width:48rem)]:gap-4",
            "[@media(max-width:48rem)]:min-h-0",
            "[@media(max-width:48rem)]:rounded-[2rem]",
            "[@media(max-width:48rem)]:p-6",
        ),
        routeIndex: cn("block", "text-accent", "text-xs", "font-extrabold", "tracking-home-eyebrow"),
        routeMarker: cn(
            "inline-flex",
            "size-16",
            "items-center",
            "justify-center",
            "rounded-[1.25rem]",
            "bg-landing-home-commercial-marker",
            "text-accent",
            "[&_svg]:size-6",
            "[@media(max-width:48rem)]:size-10",
            "[@media(max-width:48rem)]:rounded-[0.9rem]",
        ),
        routeCopy: cn(
            "max-w-home-route-copy",
            "self-end",
            "text-home-route-copy",
            "leading-home-route",
            "[@media(max-width:48rem)]:max-w-none",
            "[@media(max-width:48rem)]:self-center",
        ),
        routeArrow: cn(
            "absolute",
            "z-[3]",
            "top-[48%]",
            "right-[calc(-0.5rem_-_clamp(0.75rem,1.5vw,1.25rem))]",
            "inline-flex",
            "size-9",
            "translate-x-1/2",
            "-translate-y-1/2",
            "items-center",
            "justify-center",
            "rounded-full",
            "bg-landing-home-route-arrow",
            "text-accent",
            "shadow-landing-home-route-arrow",
            "[&_svg]:size-4",
            "[@media(max-width:48rem)]:top-auto",
            "[@media(max-width:48rem)]:right-auto",
            "[@media(max-width:48rem)]:bottom-[-1.65rem]",
            "[@media(max-width:48rem)]:left-1/2",
            "[@media(max-width:48rem)]:size-8",
            "[@media(max-width:48rem)]:translate-x-[-50%]",
            "[@media(max-width:48rem)]:translate-y-0",
            "[@media(max-width:48rem)]:rotate-90",
        ),
    },
    trust: {
        section: cn(
            "relative",
            "isolate",
            "overflow-clip",
            "border-y",
            "border-landing-inverse-line",
            "bg-landing-home-trust-scene",
            "bg-cover",
            "bg-bottom",
            "bg-no-repeat",
            "py-home-section",
            "text-surface",
            "landing-inverse-band",
            "[&_[data-component=Heading]]:text-surface",
            "forced-colors:bg-[Canvas]",
            "forced-colors:text-[CanvasText]",
        ),
        container: cn(
            "grid",
            "grid-cols-home-trust",
            "items-center",
            "gap-home-trust-grid",
            "[@media(max-width:64rem)]:grid-cols-1",
        ),
        links: cn(
            "mt-8",
            "flex",
            "flex-wrap",
            "gap-x-8",
            "gap-y-4",
            "[&>a[data-appearance=route]]:text-surface",
            "[&>a]:min-h-11",
            "[@media(max-width:48rem)]:mt-6",
        ),
        future: cn(
            "flex",
            "flex-col",
            "gap-4",
            "border-l",
            "border-landing-inverse-line",
            "py-8",
            "pl-8",
            "[&>p:first-child]:text-landing-accent-bright",
            "[&>p:first-child]:forced-colors:text-[Highlight]",
            "[&>p:last-child]:text-landing-inverse-muted",
            "[&>p:last-child]:leading-home-copy",
            "[@media(max-width:48rem)]:border-t",
            "[@media(max-width:48rem)]:border-landing-home-separator",
            "[@media(max-width:48rem)]:border-l-0",
            "[@media(max-width:48rem)]:pt-8",
            "[@media(max-width:48rem)]:pr-0",
            "[@media(max-width:48rem)]:pb-0",
            "[@media(max-width:48rem)]:pl-0",
        ),
    },
    nextPath: {
        section: cn("bg-surface", "py-home-section"),
        ideas: cn("border-b", "border-landing-home-separator", "pb-16"),
        routes: cn(
            "grid",
            "grid-cols-3",
            "gap-8",
            "pt-12",
            "[@media(max-width:48rem)]:grid-cols-2",
            "[@media(max-width:32rem)]:grid-cols-1",
        ),
        group: cn(
            "grid",
            "min-w-0",
            "gap-4",
            "[&>[data-component=Text]:first-child]:tracking-home-eyebrow",
            "[&>[data-component=Text]:first-child]:text-accent",
            "[&>[data-component=Text]:first-child]:uppercase",
            "[&>[data-component=Text]:first-child]:forced-colors:text-[Highlight]",
        ),
        routeList: cn("m-0", "grid", "list-none", "gap-2", "p-0", "[&_a]:min-h-11"),
    },
} as const

/** Select route-card placement and stack alignment from its position. */
export const homeCommercialRouteStepClassName = (index: number) =>
    cn(
        "relative",
        "z-[1]",
        "grid",
        "min-h-[15.5rem]",
        "grid-rows-[auto_auto_1fr]",
        "content-start",
        "gap-5",
        "rounded-[2rem]",
        "bg-landing-home-commercial-card",
        "p-7",
        "shadow-landing-home-commercial-card",
        index === 0 && "translate-y-[1.8rem]",
        index === 1 && "-translate-y-[0.4rem]",
        index === 2 && "translate-y-[3.8rem]",
        "[@media(max-width:48rem)]:w-[92%]",
        "[@media(max-width:48rem)]:min-h-[9.5rem]",
        "[@media(max-width:48rem)]:grid-cols-home-commercial-step-mobile",
        "[@media(max-width:48rem)]:grid-rows-[auto]",
        "[@media(max-width:48rem)]:items-center",
        "[@media(max-width:48rem)]:gap-x-4",
        "[@media(max-width:48rem)]:gap-y-[0.6rem]",
        "[@media(max-width:48rem)]:rounded-3xl",
        "[@media(max-width:48rem)]:p-5",
        "[@media(max-width:48rem)]:translate-y-0",
        index === 1 && "[@media(max-width:48rem)]:justify-self-end",
        index !== 1 && "[@media(max-width:48rem)]:justify-self-start",
    )

/** Select the visual token roles for each commercial route marker. */
export const homeCommercialRouteMarkerClassName = (index: number) =>
    cn(
        CLASS_NAMES.commercial.routeMarker,
        index === 1 && "bg-landing-home-commercial-marker-active",
        index === 1 && "text-surface",
        index === 2 && "bg-landing-home-commercial-marker-muted",
        index === 2 && "text-surface",
    )

/** Keep the four role artworks' crop transforms attached to their own image class. */
export const homeRoleImageClassName = (index: number) =>
    cn(
        "block",
        "h-full",
        "w-full",
        "object-contain",
        "object-bottom",
        "origin-bottom",
        index === 0 && "transform-[var(--landing-home-role-image-human)]",
        index === 1 && "transform-[var(--landing-home-role-image-ai)]",
        index === 2 && "transform-[var(--landing-home-role-image-system)]",
        index === 3 && "transform-[var(--landing-home-role-image-outcome)]",
    )
