import { cn } from "@heroui/react"
import styles from "./ExplorePages.module.css"

/** Colocated class contract for the public exploration page family. */
export const CLASS_NAMES = {
    page: cn(styles.page),
    hero: cn(styles.hero),
    section: cn(styles.section),
    heroInner: cn(styles.heroInner),
    heroCopy: cn(styles.heroCopy),
    eyebrow: cn(styles.eyebrow),
    heroModel: cn(styles.heroModel),
    heroModelTop: cn(styles.heroModelTop),
    heroModelPulse: cn(styles.heroModelPulse),
    heroModelList: cn(styles.heroModelList),
    heroModelIndex: cn(styles.heroModelIndex),
    heroModelIcon: cn(styles.heroModelIcon),
    heroModelNext: cn(styles.heroModelNext),
    signaturePanel: cn(styles.signaturePanel),
    signatureIcon: cn(styles.signatureIcon),
    inlineSequence: cn(styles.inlineSequence),
    actionRow: cn(styles.actionRow),
    sectionSoft: cn(styles.section, styles.sectionSoft),
    sectionDark: cn(styles.section, styles.sectionDark),
    sectionBurgundy: cn(styles.section, styles.sectionBurgundy),
    sectionInner: cn(styles.sectionInner),
    sectionSplit: cn(styles.sectionSplit),
    stack: cn(styles.stack),
    flow: cn(styles.flow),
    flowIndex: cn(styles.flowIndex),
    flowTitle: cn(styles.flowTitle),
    flowBody: cn(styles.flowBody),
    contractGrid: cn(styles.contractGrid),
    actorGrid: cn(styles.actorGrid),
    valueGrid: cn(styles.valueGrid),
    ideaGrid: cn(styles.ideaGrid),
    typeGrid: cn(styles.typeGrid),
    pathGrid: cn(styles.pathGrid),
    definitionGrid: cn(styles.definitionGrid),
    card: cn(styles.card),
    pathIndex: cn(styles.pathIndex),
    actor: cn(styles.actor),
    actorIndex: cn(styles.actorIndex),
    ideaCard: cn(styles.ideaCard),
    ideaCardFeatured: cn(styles.ideaCard, styles.ideaCardFeatured),
    editorialMark: cn(styles.editorialMark),
    routeResult: cn(styles.routeResult),
    truthNotice: cn(styles.truthNotice),
    stepList: cn(styles.stepList),
    stepCopy: cn(styles.stepCopy),
    plainList: cn(styles.plainList),
    linkList: cn(styles.linkList),
    quote: cn(styles.quote),
    topicList: cn(styles.topicList),
    ideaMetaLine: cn(styles.ideaMetaLine),
    articleHero: cn(styles.articleHero),
    articleHeader: cn(styles.articleHeader),
    articleThesis: cn(styles.articleThesis),
    articleMeta: cn(styles.articleMeta),
    articleBody: cn(styles.articleBody),
    articleSection: cn(styles.articleSection),
    articleSectionIndex: cn(styles.articleSectionIndex),
    intentForm: cn(styles.intentForm),
    intentGrid: cn(styles.intentGrid),
    intentOption: cn(styles.intentOption),
} as const

/** Route-section tone variants remain imported class values at the render boundary. */
export const SECTION_CLASS_NAMES = {
    default: CLASS_NAMES.section,
    soft: CLASS_NAMES.sectionSoft,
    dark: CLASS_NAMES.sectionDark,
    burgundy: CLASS_NAMES.sectionBurgundy,
} as const
