import { cn } from "@heroui/react"

/** Shared hero layout roles for each product page's copy and visual. */
export const PRODUCT_HERO_CLASS_NAMES = {
    root: cn(
        "relative",
        "isolate",
        "overflow-clip",
        "min-h-[calc(100dvh-var(--landing-header-height))]",
        "bg-[image:var(--product-hero-background)]",
        "max-[769px]:min-h-0",
        "forced-colors:bg-[Canvas]",
        "forced-colors:text-[CanvasText]",
        "before:absolute",
        "before:-z-10",
        "before:inset-[-18%_-8%_auto_auto]",
        "before:aspect-square",
        "before:w-[min(34rem,48vw)]",
        "before:rounded-full",
        "before:border-[7rem]",
        "before:border-solid",
        "before:border-[var(--product-hero-ring)]",
        "before:content-['']",
    ),
    applicationsRoot: cn("bg-[image:var(--product-applications-hero-background)]"),
    inner: cn(
        "grid",
        "min-h-[calc(100dvh-var(--landing-header-height))]",
        "grid-cols-[0.95fr_1.05fr]",
        "items-center",
        "gap-[clamp(2.5rem,7vw,7rem)]",
        "py-[clamp(4rem,9vw,7rem)]",
        "max-lg:min-h-0",
        "min-[769px]:max-lg:grid-cols-2",
        "max-[769px]:grid-cols-1",
        "max-[769px]:gap-8",
        "max-[769px]:py-14",
    ),
    copy: cn("flex", "max-w-3xl", "flex-col", "items-start", "gap-4"),
    actionRow: cn(
        "mt-3",
        "flex",
        "flex-wrap",
        "items-center",
        "gap-x-4",
        "gap-y-3",
        "max-[769px]:flex-col",
        "max-[769px]:items-stretch",
        "max-[769px]:[&>*]:w-full",
        "max-[769px]:[&>*]:justify-center",
    ),
    eyebrow: cn("rounded-full", "bg-accent/8", "px-3", "py-2", "tracking-[0.14em]", "uppercase"),
    title: cn("[&>h1]:max-w-[13ch]", "[&>h1]:text-balance"),
    supporting: cn("max-w-[44rem]", "leading-[1.75]"),
    visual: cn("grid", "min-w-0", "content-center", "gap-4", "max-[769px]:w-full"),
    canvas: cn(
        "relative",
        "isolate",
        "min-h-[clamp(23rem,42vw,34rem)]",
        "overflow-hidden",
        "rounded-[clamp(1.75rem,4vw,3.5rem)]",
        "bg-[image:var(--product-hero-canvas-background)]",
        "shadow-[var(--product-hero-canvas-shadow)]",
        "backdrop-blur-[16px]",
        "max-[769px]:min-h-[25rem]",
    ),
    canvasNivoOs: cn(
        "before:absolute",
        "before:inset-0",
        "before:-z-10",
        "before:bg-[url('/images/backgrounds/nivo-blue-planet-v1.png')]",
        "before:bg-cover",
        "before:bg-center",
        "before:opacity-[0.22]",
        "before:mix-blend-multiply",
        "before:content-['']",
    ),
    canvasResponsibility: cn("bg-[image:var(--product-responsibility-canvas-background)]"),
    orbit: cn(
        "absolute",
        "inset-[12%_13%]",
        "rotate-[-13deg]",
        "rounded-[50%]",
        "border",
        "border-[var(--product-hero-orbit)]",
        "before:absolute",
        "before:inset-[13%]",
        "before:rounded-[inherit]",
        "before:border",
        "before:border-dashed",
        "before:border-[var(--product-hero-orbit-inner)]",
        "before:content-['']",
        "after:absolute",
        "after:inset-[30%]",
        "after:rounded-[inherit]",
        "after:border",
        "after:border-solid",
        "after:border-[var(--product-hero-orbit-accent)]",
        "after:content-['']",
    ),
    core: cn(
        "absolute",
        "left-1/2",
        "top-1/2",
        "z-[2]",
        "flex",
        "size-[clamp(8.5rem,16vw,11rem)]",
        "rotate-[-4deg]",
        "flex-col",
        "items-center",
        "justify-center",
        "gap-[0.4rem]",
        "rounded-[2.25rem]",
        "bg-[image:var(--product-hero-core-background)]",
        "text-surface",
        "shadow-[var(--product-hero-core-shadow)]",
        "[-translate-x:50%]",
        "[-translate-y:50%]",
    ),
    coreIcon: cn("[&>svg]:size-8"),
    coreName: cn("text-[1.2rem]", "font-bold", "tracking-[-0.02em]"),
    coreLabel: cn("text-[0.67rem]", "text-surface/74"),
    nodes: cn("absolute", "inset-0", "m-0", "list-none", "p-0"),
    node: cn(
        "absolute",
        "z-[3]",
        "flex",
        "w-[clamp(8rem,14vw,10rem)]",
        "items-center",
        "gap-[0.55rem]",
        "rounded-2xl",
        "bg-surface/92",
        "px-[0.9rem]",
        "py-3",
        "text-[0.73rem]",
        "font-bold",
        "text-background-inverse",
        "shadow-[var(--product-hero-node-shadow)]",
        "max-[769px]:w-[7.5rem]",
    ),
    nodeIcon: cn("text-accent", "[&>svg]:size-5"),
    artwork: cn(
        "absolute",
        "inset-[7%_-4%_-4%_27%]",
        "z-[1]",
        "flex",
        "items-end",
        "justify-end",
        "max-[769px]:inset-[10%_-10%_9%_17%]",
    ),
    artworkImage: cn("size-full", "object-contain", "object-right-bottom", "drop-shadow-[var(--product-artwork-shadow)]"),
    responsibility: cn(
        "absolute",
        "left-[8%]",
        "top-[20%]",
        "z-[2]",
        "grid",
        "w-[clamp(10rem,19vw,13rem)]",
        "gap-[0.45rem]",
        "rounded-3xl",
        "bg-[var(--product-responsibility-surface)]",
        "p-[1.3rem]",
        "text-surface",
        "shadow-[var(--product-responsibility-shadow)]",
        "max-[769px]:left-[4%]",
        "max-[769px]:top-[10%]",
    ),
    responsibilityIcon: cn(
        "grid",
        "size-[2.6rem]",
        "place-items-center",
        "rounded-[0.8rem]",
        "bg-accent",
        "[&>svg]:size-6",
    ),
    responsibilityMuted: cn("text-[var(--product-responsibility-muted)]"),
    responsibilityTitle: cn("text-[1.15rem]"),
    steps: cn(
        "absolute",
        "bottom-[5%]",
        "left-[5%]",
        "right-[5%]",
        "z-[3]",
        "m-0",
        "grid",
        "grid-cols-3",
        "gap-2",
        "list-none",
        "p-0",
    ),
    step: cn(
        "grid",
        "gap-[0.35rem]",
        "rounded-2xl",
        "bg-surface/88",
        "p-[0.9rem]",
        "shadow-[var(--product-hero-step-shadow)]",
        "backdrop-blur-[12px]",
    ),
    stepIndex: cn("text-[0.7rem]", "font-extrabold", "text-accent"),
    stepTitle: cn("text-[0.78rem]"),
    gallery: cn(
        "grid",
        "min-h-[clamp(25rem,45vw,35rem)]",
        "grid-cols-2",
        "gap-[0.85rem]",
        "rounded-[clamp(1.75rem,4vw,3.5rem)]",
        "bg-surface/46",
        "p-[0.85rem]",
        "shadow-[var(--product-hero-canvas-shadow)]",
        "backdrop-blur-[16px]",
        "max-[769px]:min-h-[25rem]",
    ),
    galleryCard: cn(
        "relative",
        "grid",
        "min-h-48",
        "min-w-0",
        "grid-rows-[1fr_auto]",
        "overflow-hidden",
        "rounded-3xl",
        "bg-[image:var(--product-gallery-card-background)]",
        "p-[0.55rem]",
        "shadow-[var(--product-gallery-card-shadow)]",
    ),
    galleryCardOffset: cn("translate-y-7", "max-[769px]:translate-y-0"),
    galleryImage: cn("size-full", "min-h-0", "object-contain", "object-bottom"),
    galleryCaption: cn(
        "flex",
        "items-center",
        "gap-[0.55rem]",
        "rounded-[0.9rem]",
        "bg-surface/82",
        "px-3",
        "py-[0.65rem]",
        "text-[0.72rem]",
        "font-[750]",
        "text-background-inverse",
        "backdrop-blur-[10px]",
    ),
    galleryIndex: cn("text-[0.65rem]", "text-accent"),
    signal: cn(
        "relative",
        "grid",
        "gap-5",
        "rounded-[1.25rem]",
        "bg-surface/82",
        "p-[clamp(1.5rem,4vw,2.5rem)]",
        "shadow-[var(--product-hero-signal-shadow)]",
        "backdrop-blur-[14px]",
        "before:h-1",
        "before:w-10",
        "before:rounded-full",
        "before:bg-accent",
        "before:content-['']",
        "max-[769px]:rounded-2xl",
    ),
    signalLabel: cn("tracking-[0.14em]", "uppercase"),
    signalValue: cn(
        "text-[clamp(1.2rem,2.4vw,1.75rem)]",
        "font-[750]",
        "leading-[1.25]",
        "text-landing-accent-ink",
    ),
    signalNote: cn("text-[0.9rem]", "leading-[1.6]", "text-landing-ink-soft"),
    nodePositionBusiness: cn("left-[10%]", "top-[9%]", "max-[769px]:left-[4%]", "max-[769px]:top-[7%]"),
    nodePositionHuman: cn("right-[8%]", "top-[17%]", "max-[769px]:right-[4%]", "max-[769px]:top-[12%]"),
    nodePositionAi: cn("bottom-[14%]", "right-[8%]", "max-[769px]:bottom-[10%]", "max-[769px]:right-[4%]"),
    nodePositionOutcome: cn("bottom-[9%]", "left-[8%]", "max-[769px]:bottom-[7%]", "max-[769px]:left-[4%]"),
} as const

/** Hero root background follows the page-specific product palette. */
export const productHeroRootClassName = (page: string) =>
    cn(PRODUCT_HERO_CLASS_NAMES.root, page === "applications" && PRODUCT_HERO_CLASS_NAMES.applicationsRoot)

/** The visual canvas receives a page-specific background when one is defined. */
export const productHeroCanvasClassName = (page: string) =>
    cn(
        PRODUCT_HERO_CLASS_NAMES.canvas,
        page === "nivoOs" && PRODUCT_HERO_CLASS_NAMES.canvasNivoOs,
        page === "systemOfResponsibility" && PRODUCT_HERO_CLASS_NAMES.canvasResponsibility,
    )

/** Operating nodes use fixed positions to form the product's four-step orbit. */
export const productHeroNodeClassName = (index: number) => {
    const positions = [
        PRODUCT_HERO_CLASS_NAMES.nodePositionBusiness,
        PRODUCT_HERO_CLASS_NAMES.nodePositionHuman,
        PRODUCT_HERO_CLASS_NAMES.nodePositionAi,
        PRODUCT_HERO_CLASS_NAMES.nodePositionOutcome,
    ]
    return cn(PRODUCT_HERO_CLASS_NAMES.node, positions[index] ?? PRODUCT_HERO_CLASS_NAMES.nodePositionBusiness)
}

/** Product gallery cards alternate vertically on wider layouts. */
export const productHeroGalleryCardClassName = (index: number) =>
    cn(PRODUCT_HERO_CLASS_NAMES.galleryCard, index === 3 && PRODUCT_HERO_CLASS_NAMES.galleryCardOffset)
